/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.19.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// AggregationFieldDto
    /// </summary>
    [DataContract(Name = "AggregationFieldDto")]
    public partial class AggregationFieldDto
    {
        /// <summary>
        /// Defines Operations
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OperationsEnum
        {
            /// <summary>
            /// Enum Count for value: count
            /// </summary>
            [EnumMember(Value = "count")]
            Count = 1,

            /// <summary>
            /// Enum Sum for value: sum
            /// </summary>
            [EnumMember(Value = "sum")]
            Sum = 2,

            /// <summary>
            /// Enum Avg for value: avg
            /// </summary>
            [EnumMember(Value = "avg")]
            Avg = 3,

            /// <summary>
            /// Enum Min for value: min
            /// </summary>
            [EnumMember(Value = "min")]
            Min = 4,

            /// <summary>
            /// Enum Max for value: max
            /// </summary>
            [EnumMember(Value = "max")]
            Max = 5
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AggregationFieldDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AggregationFieldDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="AggregationFieldDto" /> class.
        /// </summary>
        /// <param name="field">Metadata field name to aggregate (e.g., \&quot;score\&quot;, \&quot;playTime\&quot;) (required).</param>
        /// <param name="operations">Aggregation operations to perform (required).</param>
        public AggregationFieldDto(string field = default(string), List<OperationsEnum> operations = default(List<OperationsEnum>))
        {
            // to ensure "field" is required (not null)
            if (field == null)
            {
                throw new ArgumentNullException("field is a required property for AggregationFieldDto and cannot be null");
            }
            this.Field = field;
            // to ensure "operations" is required (not null)
            if (operations == null)
            {
                throw new ArgumentNullException("operations is a required property for AggregationFieldDto and cannot be null");
            }
            this.Operations = operations;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Metadata field name to aggregate (e.g., \&quot;score\&quot;, \&quot;playTime\&quot;)
        /// </summary>
        /// <value>Metadata field name to aggregate (e.g., \&quot;score\&quot;, \&quot;playTime\&quot;)</value>
        /*
        <example>score</example>
        */
        [DataMember(Name = "field", IsRequired = true, EmitDefaultValue = true)]
        public string Field { get; set; }

        /// <summary>
        /// Aggregation operations to perform
        /// </summary>
        /// <value>Aggregation operations to perform</value>
        /*
        <example>[&quot;sum&quot;,&quot;avg&quot;,&quot;min&quot;,&quot;max&quot;]</example>
        */
        [DataMember(Name = "operations", IsRequired = true, EmitDefaultValue = true)]
        public List<AggregationFieldDto.OperationsEnum> Operations { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AggregationFieldDto {\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Operations: ").Append(Operations).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
