/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.27.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// AggregatePlaySessionResponseDto
    /// </summary>
    [DataContract(Name = "AggregatePlaySessionResponseDto")]
    public partial class AggregatePlaySessionResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AggregatePlaySessionResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AggregatePlaySessionResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="AggregatePlaySessionResponseDto" /> class.
        /// </summary>
        /// <param name="totalCount">Total count of sessions matching the filter criteria (required).</param>
        /// <param name="finishedCount">Count of finished sessions (end_time is not null) (required).</param>
        /// <param name="playingCount">Count of sessions currently playing (end_time is null) (required).</param>
        /// <param name="aggregations">Aggregation results for each requested field.</param>
        public AggregatePlaySessionResponseDto(decimal totalCount = default(decimal), decimal finishedCount = default(decimal), decimal playingCount = default(decimal), List<FieldAggregationResultDto> aggregations = default(List<FieldAggregationResultDto>))
        {
            this.TotalCount = totalCount;
            this.FinishedCount = finishedCount;
            this.PlayingCount = playingCount;
            this.Aggregations = aggregations;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Total count of sessions matching the filter criteria
        /// </summary>
        /// <value>Total count of sessions matching the filter criteria</value>
        /*
        <example>250</example>
        */
        [DataMember(Name = "totalCount", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalCount { get; set; }

        /// <summary>
        /// Count of finished sessions (end_time is not null)
        /// </summary>
        /// <value>Count of finished sessions (end_time is not null)</value>
        /*
        <example>200</example>
        */
        [DataMember(Name = "finishedCount", IsRequired = true, EmitDefaultValue = true)]
        public decimal FinishedCount { get; set; }

        /// <summary>
        /// Count of sessions currently playing (end_time is null)
        /// </summary>
        /// <value>Count of sessions currently playing (end_time is null)</value>
        /*
        <example>50</example>
        */
        [DataMember(Name = "playingCount", IsRequired = true, EmitDefaultValue = true)]
        public decimal PlayingCount { get; set; }

        /// <summary>
        /// Aggregation results for each requested field
        /// </summary>
        /// <value>Aggregation results for each requested field</value>
        [DataMember(Name = "aggregations", EmitDefaultValue = false)]
        public List<FieldAggregationResultDto> Aggregations { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AggregatePlaySessionResponseDto {\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("  FinishedCount: ").Append(FinishedCount).Append("\n");
            sb.Append("  PlayingCount: ").Append(PlayingCount).Append("\n");
            sb.Append("  Aggregations: ").Append(Aggregations).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
