/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.34.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// ClusteredRouteDto
    /// </summary>
    [DataContract(Name = "ClusteredRouteDto")]
    public partial class ClusteredRouteDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClusteredRouteDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ClusteredRouteDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ClusteredRouteDto" /> class.
        /// </summary>
        /// <param name="id">Clustered route ID (required).</param>
        /// <param name="trajectoryPoints">Averaged trajectory points (clustered) (required).</param>
        /// <param name="occurrenceCount">Number of times this route pattern was taken (required).</param>
        /// <param name="successCount">Number of times this route led to success (required).</param>
        /// <param name="avgDurationMs">Average duration in milliseconds.</param>
        /// <param name="successRate">Success rate (0-1) (required).</param>
        /// <param name="passesNearCluster">Whether this route passes near the cluster without triggering the event (required).</param>
        /// <param name="clusterNearCount">Number of times this route safely passed near the cluster (required).</param>
        public ClusteredRouteDto(decimal id = default(decimal), List<ClusteredRouteDtoTrajectoryPointsInner> trajectoryPoints = default(List<ClusteredRouteDtoTrajectoryPointsInner>), int occurrenceCount = default(int), int successCount = default(int), decimal avgDurationMs = default(decimal), decimal successRate = default(decimal), bool passesNearCluster = default(bool), int clusterNearCount = default(int))
        {
            this.Id = id;
            // to ensure "trajectoryPoints" is required (not null)
            if (trajectoryPoints == null)
            {
                throw new ArgumentNullException("trajectoryPoints is a required property for ClusteredRouteDto and cannot be null");
            }
            this.TrajectoryPoints = trajectoryPoints;
            this.OccurrenceCount = occurrenceCount;
            this.SuccessCount = successCount;
            this.SuccessRate = successRate;
            this.PassesNearCluster = passesNearCluster;
            this.ClusterNearCount = clusterNearCount;
            this.AvgDurationMs = avgDurationMs;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Clustered route ID
        /// </summary>
        /// <value>Clustered route ID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public decimal Id { get; set; }

        /// <summary>
        /// Averaged trajectory points (clustered)
        /// </summary>
        /// <value>Averaged trajectory points (clustered)</value>
        [DataMember(Name = "trajectory_points", IsRequired = true, EmitDefaultValue = true)]
        public List<ClusteredRouteDtoTrajectoryPointsInner> TrajectoryPoints { get; set; }

        /// <summary>
        /// Number of times this route pattern was taken
        /// </summary>
        /// <value>Number of times this route pattern was taken</value>
        [DataMember(Name = "occurrence_count", IsRequired = true, EmitDefaultValue = true)]
        public int OccurrenceCount { get; set; }

        /// <summary>
        /// Number of times this route led to success
        /// </summary>
        /// <value>Number of times this route led to success</value>
        [DataMember(Name = "success_count", IsRequired = true, EmitDefaultValue = true)]
        public int SuccessCount { get; set; }

        /// <summary>
        /// Average duration in milliseconds
        /// </summary>
        /// <value>Average duration in milliseconds</value>
        [DataMember(Name = "avg_duration_ms", EmitDefaultValue = false)]
        public decimal AvgDurationMs { get; set; }

        /// <summary>
        /// Success rate (0-1)
        /// </summary>
        /// <value>Success rate (0-1)</value>
        [DataMember(Name = "success_rate", IsRequired = true, EmitDefaultValue = true)]
        public decimal SuccessRate { get; set; }

        /// <summary>
        /// Whether this route passes near the cluster without triggering the event
        /// </summary>
        /// <value>Whether this route passes near the cluster without triggering the event</value>
        [DataMember(Name = "passes_near_cluster", IsRequired = true, EmitDefaultValue = true)]
        public bool PassesNearCluster { get; set; }

        /// <summary>
        /// Number of times this route safely passed near the cluster
        /// </summary>
        /// <value>Number of times this route safely passed near the cluster</value>
        [DataMember(Name = "cluster_near_count", IsRequired = true, EmitDefaultValue = true)]
        public int ClusterNearCount { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ClusteredRouteDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TrajectoryPoints: ").Append(TrajectoryPoints).Append("\n");
            sb.Append("  OccurrenceCount: ").Append(OccurrenceCount).Append("\n");
            sb.Append("  SuccessCount: ").Append(SuccessCount).Append("\n");
            sb.Append("  AvgDurationMs: ").Append(AvgDurationMs).Append("\n");
            sb.Append("  SuccessRate: ").Append(SuccessRate).Append("\n");
            sb.Append("  PassesNearCluster: ").Append(PassesNearCluster).Append("\n");
            sb.Append("  ClusterNearCount: ").Append(ClusterNearCount).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
