/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.19.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// CreateGameApiKeyDto
    /// </summary>
    [DataContract(Name = "CreateGameApiKeyDto")]
    public partial class CreateGameApiKeyDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateGameApiKeyDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateGameApiKeyDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateGameApiKeyDto" /> class.
        /// </summary>
        /// <param name="name">APIキーの識別名 (required).</param>
        /// <param name="projectIds">初期段階でアクセス可能にするプロジェクトIDの配列（オプション）.</param>
        public CreateGameApiKeyDto(string name = default(string), List<decimal> projectIds = default(List<decimal>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateGameApiKeyDto and cannot be null");
            }
            this.Name = name;
            this.ProjectIds = projectIds;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// APIキーの識別名
        /// </summary>
        /// <value>APIキーの識別名</value>
        /*
        <example>My Unity Game Client</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// 初期段階でアクセス可能にするプロジェクトIDの配列（オプション）
        /// </summary>
        /// <value>初期段階でアクセス可能にするプロジェクトIDの配列（オプション）</value>
        /*
        <example>[1,2,3]</example>
        */
        [DataMember(Name = "projectIds", EmitDefaultValue = false)]
        public List<decimal> ProjectIds { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateGameApiKeyDto {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ProjectIds: ").Append(ProjectIds).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
