/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.31.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// CreateHeatmapDto
    /// </summary>
    [DataContract(Name = "CreateHeatmapDto")]
    public partial class CreateHeatmapDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateHeatmapDto" /> class.
        /// </summary>
        /// <param name="stepSize">Heatmap width.</param>
        /// <param name="zVisible">Whether to display the Z-axis.</param>
        /// <param name="sessionIds">Filter by specific session IDs (for project heatmap). Cannot be used together with searchQuery..</param>
        /// <param name="searchQuery">Search query to filter sessions (for project heatmap). Cannot be used together with sessionIds. Use the same parameters as the search summary endpoint..</param>
        public CreateHeatmapDto(decimal stepSize = default(decimal), bool zVisible = default(bool), List<decimal> sessionIds = default(List<decimal>), HeatmapSearchQueryDto searchQuery = default(HeatmapSearchQueryDto))
        {
            this.StepSize = stepSize;
            this.ZVisible = zVisible;
            this.SessionIds = sessionIds;
            this.SearchQuery = searchQuery;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Heatmap width
        /// </summary>
        /// <value>Heatmap width</value>
        /*
        <example>300</example>
        */
        [DataMember(Name = "stepSize", EmitDefaultValue = false)]
        public decimal StepSize { get; set; }

        /// <summary>
        /// Whether to display the Z-axis
        /// </summary>
        /// <value>Whether to display the Z-axis</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "zVisible", EmitDefaultValue = true)]
        public bool ZVisible { get; set; }

        /// <summary>
        /// Filter by specific session IDs (for project heatmap). Cannot be used together with searchQuery.
        /// </summary>
        /// <value>Filter by specific session IDs (for project heatmap). Cannot be used together with searchQuery.</value>
        /*
        <example>[1,2,3]</example>
        */
        [DataMember(Name = "sessionIds", EmitDefaultValue = false)]
        public List<decimal> SessionIds { get; set; }

        /// <summary>
        /// Search query to filter sessions (for project heatmap). Cannot be used together with sessionIds. Use the same parameters as the search summary endpoint.
        /// </summary>
        /// <value>Search query to filter sessions (for project heatmap). Cannot be used together with sessionIds. Use the same parameters as the search summary endpoint.</value>
        [DataMember(Name = "searchQuery", EmitDefaultValue = false)]
        public HeatmapSearchQueryDto SearchQuery { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateHeatmapDto {\n");
            sb.Append("  StepSize: ").Append(StepSize).Append("\n");
            sb.Append("  ZVisible: ").Append(ZVisible).Append("\n");
            sb.Append("  SessionIds: ").Append(SessionIds).Append("\n");
            sb.Append("  SearchQuery: ").Append(SearchQuery).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
