/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.34.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// CreateEmbedUrlDto
    /// </summary>
    [DataContract(Name = "CreateEmbedUrlDto")]
    public partial class CreateEmbedUrlDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateEmbedUrlDto" /> class.
        /// </summary>
        /// <param name="expiresInHours">有効期限（時間単位）。0.5〜8760の範囲で指定可能。デフォルト: 4時間 (default to 4M).</param>
        public CreateEmbedUrlDto(decimal expiresInHours = 4M)
        {
            this.ExpiresInHours = expiresInHours;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// 有効期限（時間単位）。0.5〜8760の範囲で指定可能。デフォルト: 4時間
        /// </summary>
        /// <value>有効期限（時間単位）。0.5〜8760の範囲で指定可能。デフォルト: 4時間</value>
        /*
        <example>4</example>
        */
        [DataMember(Name = "expiresInHours", EmitDefaultValue = false)]
        public decimal ExpiresInHours { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateEmbedUrlDto {\n");
            sb.Append("  ExpiresInHours: ").Append(ExpiresInHours).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
