/*
 * API Documentation
 *
 * The API description
 *
 * The version of the OpenAPI document: 1.13.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// EventRawCoordinateDto
    /// </summary>
    [DataContract(Name = "EventRawCoordinateDto")]
    public partial class EventRawCoordinateDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventRawCoordinateDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventRawCoordinateDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventRawCoordinateDto" /> class.
        /// </summary>
        /// <param name="x">X coordinate (required).</param>
        /// <param name="y">Y coordinate (required).</param>
        /// <param name="z">Z coordinate (required).</param>
        /// <param name="eventTimestamp">Event timestamp (milliseconds) (required).</param>
        /// <param name="sessionId">Session ID (required).</param>
        /// <param name="playerId">Player ID (required).</param>
        public EventRawCoordinateDto(decimal x = default(decimal), decimal y = default(decimal), decimal z = default(decimal), decimal eventTimestamp = default(decimal), string sessionId = default(string), string playerId = default(string))
        {
            this.X = x;
            this.Y = y;
            this.Z = z;
            this.EventTimestamp = eventTimestamp;
            // to ensure "sessionId" is required (not null)
            if (sessionId == null)
            {
                throw new ArgumentNullException("sessionId is a required property for EventRawCoordinateDto and cannot be null");
            }
            this.SessionId = sessionId;
            // to ensure "playerId" is required (not null)
            if (playerId == null)
            {
                throw new ArgumentNullException("playerId is a required property for EventRawCoordinateDto and cannot be null");
            }
            this.PlayerId = playerId;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// X coordinate
        /// </summary>
        /// <value>X coordinate</value>
        [DataMember(Name = "x", IsRequired = true, EmitDefaultValue = true)]
        public decimal X { get; set; }

        /// <summary>
        /// Y coordinate
        /// </summary>
        /// <value>Y coordinate</value>
        [DataMember(Name = "y", IsRequired = true, EmitDefaultValue = true)]
        public decimal Y { get; set; }

        /// <summary>
        /// Z coordinate
        /// </summary>
        /// <value>Z coordinate</value>
        [DataMember(Name = "z", IsRequired = true, EmitDefaultValue = true)]
        public decimal Z { get; set; }

        /// <summary>
        /// Event timestamp (milliseconds)
        /// </summary>
        /// <value>Event timestamp (milliseconds)</value>
        [DataMember(Name = "event_timestamp", IsRequired = true, EmitDefaultValue = true)]
        public decimal EventTimestamp { get; set; }

        /// <summary>
        /// Session ID
        /// </summary>
        /// <value>Session ID</value>
        [DataMember(Name = "session_id", IsRequired = true, EmitDefaultValue = true)]
        public string SessionId { get; set; }

        /// <summary>
        /// Player ID
        /// </summary>
        /// <value>Player ID</value>
        [DataMember(Name = "player_id", IsRequired = true, EmitDefaultValue = true)]
        public string PlayerId { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventRawCoordinateDto {\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Z: ").Append(Z).Append("\n");
            sb.Append("  EventTimestamp: ").Append(EventTimestamp).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  PlayerId: ").Append(PlayerId).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
