/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.29.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// EventClusterDetailDto
    /// </summary>
    [DataContract(Name = "EventClusterDetailDto")]
    public partial class EventClusterDetailDto
    {
        /// <summary>
        /// Type of event this cluster represents
        /// </summary>
        /// <value>Type of event this cluster represents</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EventTypeEnum
        {
            /// <summary>
            /// Enum Death for value: death
            /// </summary>
            [EnumMember(Value = "death")]
            Death = 1,

            /// <summary>
            /// Enum Success for value: success
            /// </summary>
            [EnumMember(Value = "success")]
            Success = 2
        }


        /// <summary>
        /// Type of event this cluster represents
        /// </summary>
        /// <value>Type of event this cluster represents</value>
        [DataMember(Name = "event_type", IsRequired = true, EmitDefaultValue = true)]
        public EventTypeEnum EventType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventClusterDetailDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventClusterDetailDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventClusterDetailDto" /> class.
        /// </summary>
        /// <param name="id">Cluster ID (required).</param>
        /// <param name="clusterCenterX">Center X coordinate of the cluster (required).</param>
        /// <param name="clusterCenterY">Center Y coordinate of the cluster (required).</param>
        /// <param name="clusterCenterZ">Center Z coordinate of the cluster (required).</param>
        /// <param name="clusterRadius">Radius of the cluster (meters) (required).</param>
        /// <param name="rawEventCount">Total raw event count in this cluster (required).</param>
        /// <param name="eventType">Type of event this cluster represents (required).</param>
        /// <param name="playerId">Player ID this cluster belongs to (required).</param>
        /// <param name="mapName">Map name.</param>
        /// <param name="rawCoordinates">Raw event coordinates in this cluster (required).</param>
        /// <param name="routes">Raw routes - individual player movement logs leading to this cluster (required).</param>
        /// <param name="clusteredRoutes">Clustered routes - aggregated/averaged route patterns for statistics (required).</param>
        /// <param name="improvements">Improvement route recommendations (required).</param>
        /// <param name="createdAt">Cluster creation timestamp (required).</param>
        /// <param name="updatedAt">Cluster last update timestamp (required).</param>
        public EventClusterDetailDto(decimal id = default(decimal), decimal clusterCenterX = default(decimal), decimal clusterCenterY = default(decimal), decimal clusterCenterZ = default(decimal), decimal clusterRadius = default(decimal), int rawEventCount = default(int), EventTypeEnum eventType = default(EventTypeEnum), string playerId = default(string), string mapName = default(string), List<EventRawCoordinateDto> rawCoordinates = default(List<EventRawCoordinateDto>), List<RawRouteDto> routes = default(List<RawRouteDto>), List<ClusteredRouteDto> clusteredRoutes = default(List<ClusteredRouteDto>), List<ImprovementRouteDto> improvements = default(List<ImprovementRouteDto>), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime))
        {
            this.Id = id;
            this.ClusterCenterX = clusterCenterX;
            this.ClusterCenterY = clusterCenterY;
            this.ClusterCenterZ = clusterCenterZ;
            this.ClusterRadius = clusterRadius;
            this.RawEventCount = rawEventCount;
            this.EventType = eventType;
            // to ensure "playerId" is required (not null)
            if (playerId == null)
            {
                throw new ArgumentNullException("playerId is a required property for EventClusterDetailDto and cannot be null");
            }
            this.PlayerId = playerId;
            // to ensure "rawCoordinates" is required (not null)
            if (rawCoordinates == null)
            {
                throw new ArgumentNullException("rawCoordinates is a required property for EventClusterDetailDto and cannot be null");
            }
            this.RawCoordinates = rawCoordinates;
            // to ensure "routes" is required (not null)
            if (routes == null)
            {
                throw new ArgumentNullException("routes is a required property for EventClusterDetailDto and cannot be null");
            }
            this.Routes = routes;
            // to ensure "clusteredRoutes" is required (not null)
            if (clusteredRoutes == null)
            {
                throw new ArgumentNullException("clusteredRoutes is a required property for EventClusterDetailDto and cannot be null");
            }
            this.ClusteredRoutes = clusteredRoutes;
            // to ensure "improvements" is required (not null)
            if (improvements == null)
            {
                throw new ArgumentNullException("improvements is a required property for EventClusterDetailDto and cannot be null");
            }
            this.Improvements = improvements;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.MapName = mapName;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Cluster ID
        /// </summary>
        /// <value>Cluster ID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public decimal Id { get; set; }

        /// <summary>
        /// Center X coordinate of the cluster
        /// </summary>
        /// <value>Center X coordinate of the cluster</value>
        [DataMember(Name = "cluster_center_x", IsRequired = true, EmitDefaultValue = true)]
        public decimal ClusterCenterX { get; set; }

        /// <summary>
        /// Center Y coordinate of the cluster
        /// </summary>
        /// <value>Center Y coordinate of the cluster</value>
        [DataMember(Name = "cluster_center_y", IsRequired = true, EmitDefaultValue = true)]
        public decimal ClusterCenterY { get; set; }

        /// <summary>
        /// Center Z coordinate of the cluster
        /// </summary>
        /// <value>Center Z coordinate of the cluster</value>
        [DataMember(Name = "cluster_center_z", IsRequired = true, EmitDefaultValue = true)]
        public decimal ClusterCenterZ { get; set; }

        /// <summary>
        /// Radius of the cluster (meters)
        /// </summary>
        /// <value>Radius of the cluster (meters)</value>
        [DataMember(Name = "cluster_radius", IsRequired = true, EmitDefaultValue = true)]
        public decimal ClusterRadius { get; set; }

        /// <summary>
        /// Total raw event count in this cluster
        /// </summary>
        /// <value>Total raw event count in this cluster</value>
        [DataMember(Name = "raw_event_count", IsRequired = true, EmitDefaultValue = true)]
        public int RawEventCount { get; set; }

        /// <summary>
        /// Player ID this cluster belongs to
        /// </summary>
        /// <value>Player ID this cluster belongs to</value>
        [DataMember(Name = "player_id", IsRequired = true, EmitDefaultValue = true)]
        public string PlayerId { get; set; }

        /// <summary>
        /// Map name
        /// </summary>
        /// <value>Map name</value>
        [DataMember(Name = "map_name", EmitDefaultValue = false)]
        public string MapName { get; set; }

        /// <summary>
        /// Raw event coordinates in this cluster
        /// </summary>
        /// <value>Raw event coordinates in this cluster</value>
        [DataMember(Name = "raw_coordinates", IsRequired = true, EmitDefaultValue = true)]
        public List<EventRawCoordinateDto> RawCoordinates { get; set; }

        /// <summary>
        /// Raw routes - individual player movement logs leading to this cluster
        /// </summary>
        /// <value>Raw routes - individual player movement logs leading to this cluster</value>
        [DataMember(Name = "routes", IsRequired = true, EmitDefaultValue = true)]
        public List<RawRouteDto> Routes { get; set; }

        /// <summary>
        /// Clustered routes - aggregated/averaged route patterns for statistics
        /// </summary>
        /// <value>Clustered routes - aggregated/averaged route patterns for statistics</value>
        [DataMember(Name = "clustered_routes", IsRequired = true, EmitDefaultValue = true)]
        public List<ClusteredRouteDto> ClusteredRoutes { get; set; }

        /// <summary>
        /// Improvement route recommendations
        /// </summary>
        /// <value>Improvement route recommendations</value>
        [DataMember(Name = "improvements", IsRequired = true, EmitDefaultValue = true)]
        public List<ImprovementRouteDto> Improvements { get; set; }

        /// <summary>
        /// Cluster creation timestamp
        /// </summary>
        /// <value>Cluster creation timestamp</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Cluster last update timestamp
        /// </summary>
        /// <value>Cluster last update timestamp</value>
        [DataMember(Name = "updated_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventClusterDetailDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ClusterCenterX: ").Append(ClusterCenterX).Append("\n");
            sb.Append("  ClusterCenterY: ").Append(ClusterCenterY).Append("\n");
            sb.Append("  ClusterCenterZ: ").Append(ClusterCenterZ).Append("\n");
            sb.Append("  ClusterRadius: ").Append(ClusterRadius).Append("\n");
            sb.Append("  RawEventCount: ").Append(RawEventCount).Append("\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  PlayerId: ").Append(PlayerId).Append("\n");
            sb.Append("  MapName: ").Append(MapName).Append("\n");
            sb.Append("  RawCoordinates: ").Append(RawCoordinates).Append("\n");
            sb.Append("  Routes: ").Append(Routes).Append("\n");
            sb.Append("  ClusteredRoutes: ").Append(ClusteredRoutes).Append("\n");
            sb.Append("  Improvements: ").Append(Improvements).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
