/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.26.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// FieldObjectLogDto
    /// </summary>
    [DataContract(Name = "FieldObjectLogDto")]
    public partial class FieldObjectLogDto
    {
        /// <summary>
        /// Event type for this log entry
        /// </summary>
        /// <value>Event type for this log entry</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EventTypeEnum
        {
            /// <summary>
            /// Enum Spawn for value: spawn
            /// </summary>
            [EnumMember(Value = "spawn")]
            Spawn = 1,

            /// <summary>
            /// Enum Move for value: move
            /// </summary>
            [EnumMember(Value = "move")]
            Move = 2,

            /// <summary>
            /// Enum Despawn for value: despawn
            /// </summary>
            [EnumMember(Value = "despawn")]
            Despawn = 3,

            /// <summary>
            /// Enum Update for value: update
            /// </summary>
            [EnumMember(Value = "update")]
            Update = 4
        }


        /// <summary>
        /// Event type for this log entry
        /// </summary>
        /// <value>Event type for this log entry</value>
        [DataMember(Name = "event_type", IsRequired = true, EmitDefaultValue = true)]
        public EventTypeEnum EventType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldObjectLogDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FieldObjectLogDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldObjectLogDto" /> class.
        /// </summary>
        /// <param name="objectId">Unique object identifier in the game (required).</param>
        /// <param name="objectType">Type of the object (required).</param>
        /// <param name="x">X coordinate (required).</param>
        /// <param name="y">Y coordinate (required).</param>
        /// <param name="z">Z coordinate.</param>
        /// <param name="offsetTimestamp">Milliseconds since session start (required).</param>
        /// <param name="eventType">Event type for this log entry (required).</param>
        /// <param name="status">Additional status data for this object (health, state, score, etc.).</param>
        public FieldObjectLogDto(string objectId = default(string), string objectType = default(string), decimal x = default(decimal), decimal y = default(decimal), decimal? z = default(decimal?), int offsetTimestamp = default(int), EventTypeEnum eventType = default(EventTypeEnum), Object status = default(Object))
        {
            // to ensure "objectId" is required (not null)
            if (objectId == null)
            {
                throw new ArgumentNullException("objectId is a required property for FieldObjectLogDto and cannot be null");
            }
            this.ObjectId = objectId;
            // to ensure "objectType" is required (not null)
            if (objectType == null)
            {
                throw new ArgumentNullException("objectType is a required property for FieldObjectLogDto and cannot be null");
            }
            this.ObjectType = objectType;
            this.X = x;
            this.Y = y;
            this.OffsetTimestamp = offsetTimestamp;
            this.EventType = eventType;
            this.Z = z;
            this.Status = status;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Unique object identifier in the game
        /// </summary>
        /// <value>Unique object identifier in the game</value>
        /*
        <example>item_123</example>
        */
        [DataMember(Name = "object_id", IsRequired = true, EmitDefaultValue = true)]
        public string ObjectId { get; set; }

        /// <summary>
        /// Type of the object
        /// </summary>
        /// <value>Type of the object</value>
        /*
        <example>health_potion</example>
        */
        [DataMember(Name = "object_type", IsRequired = true, EmitDefaultValue = true)]
        public string ObjectType { get; set; }

        /// <summary>
        /// X coordinate
        /// </summary>
        /// <value>X coordinate</value>
        [DataMember(Name = "x", IsRequired = true, EmitDefaultValue = true)]
        public decimal X { get; set; }

        /// <summary>
        /// Y coordinate
        /// </summary>
        /// <value>Y coordinate</value>
        [DataMember(Name = "y", IsRequired = true, EmitDefaultValue = true)]
        public decimal Y { get; set; }

        /// <summary>
        /// Z coordinate
        /// </summary>
        /// <value>Z coordinate</value>
        [DataMember(Name = "z", EmitDefaultValue = true)]
        public decimal? Z { get; set; }

        /// <summary>
        /// Milliseconds since session start
        /// </summary>
        /// <value>Milliseconds since session start</value>
        [DataMember(Name = "offset_timestamp", IsRequired = true, EmitDefaultValue = true)]
        public int OffsetTimestamp { get; set; }

        /// <summary>
        /// Additional status data for this object (health, state, score, etc.)
        /// </summary>
        /// <value>Additional status data for this object (health, state, score, etc.)</value>
        /*
        <example>{&quot;health&quot;:100,&quot;state&quot;:&quot;active&quot;,&quot;score&quot;:50}</example>
        */
        [DataMember(Name = "status", EmitDefaultValue = true)]
        public Object Status { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FieldObjectLogDto {\n");
            sb.Append("  ObjectId: ").Append(ObjectId).Append("\n");
            sb.Append("  ObjectType: ").Append(ObjectType).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Z: ").Append(Z).Append("\n");
            sb.Append("  OffsetTimestamp: ").Append(OffsetTimestamp).Append("\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
