/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.29.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// FieldAggregationResultDto
    /// </summary>
    [DataContract(Name = "FieldAggregationResultDto")]
    public partial class FieldAggregationResultDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldAggregationResultDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FieldAggregationResultDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldAggregationResultDto" /> class.
        /// </summary>
        /// <param name="field">Field name that was aggregated (required).</param>
        /// <param name="count">Count of sessions that have this field with numeric value (required).</param>
        /// <param name="sum">Sum of all values (if requested).</param>
        /// <param name="avg">Average value (if requested).</param>
        /// <param name="min">Minimum value (if requested).</param>
        /// <param name="max">Maximum value (if requested).</param>
        public FieldAggregationResultDto(string field = default(string), decimal count = default(decimal), decimal sum = default(decimal), decimal avg = default(decimal), decimal min = default(decimal), decimal max = default(decimal))
        {
            // to ensure "field" is required (not null)
            if (field == null)
            {
                throw new ArgumentNullException("field is a required property for FieldAggregationResultDto and cannot be null");
            }
            this.Field = field;
            this.Count = count;
            this.Sum = sum;
            this.Avg = avg;
            this.Min = min;
            this.Max = max;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Field name that was aggregated
        /// </summary>
        /// <value>Field name that was aggregated</value>
        /*
        <example>score</example>
        */
        [DataMember(Name = "field", IsRequired = true, EmitDefaultValue = true)]
        public string Field { get; set; }

        /// <summary>
        /// Count of sessions that have this field with numeric value
        /// </summary>
        /// <value>Count of sessions that have this field with numeric value</value>
        /*
        <example>150</example>
        */
        [DataMember(Name = "count", IsRequired = true, EmitDefaultValue = true)]
        public decimal Count { get; set; }

        /// <summary>
        /// Sum of all values (if requested)
        /// </summary>
        /// <value>Sum of all values (if requested)</value>
        /*
        <example>12500</example>
        */
        [DataMember(Name = "sum", EmitDefaultValue = false)]
        public decimal Sum { get; set; }

        /// <summary>
        /// Average value (if requested)
        /// </summary>
        /// <value>Average value (if requested)</value>
        /*
        <example>83.33</example>
        */
        [DataMember(Name = "avg", EmitDefaultValue = false)]
        public decimal Avg { get; set; }

        /// <summary>
        /// Minimum value (if requested)
        /// </summary>
        /// <value>Minimum value (if requested)</value>
        /*
        <example>10</example>
        */
        [DataMember(Name = "min", EmitDefaultValue = false)]
        public decimal Min { get; set; }

        /// <summary>
        /// Maximum value (if requested)
        /// </summary>
        /// <value>Maximum value (if requested)</value>
        /*
        <example>200</example>
        */
        [DataMember(Name = "max", EmitDefaultValue = false)]
        public decimal Max { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FieldAggregationResultDto {\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Sum: ").Append(Sum).Append("\n");
            sb.Append("  Avg: ").Append(Avg).Append("\n");
            sb.Append("  Min: ").Append(Min).Append("\n");
            sb.Append("  Max: ").Append(Max).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
