/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.19.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// FilterOptionsResponseDto
    /// </summary>
    [DataContract(Name = "FilterOptionsResponseDto")]
    public partial class FilterOptionsResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterOptionsResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FilterOptionsResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterOptionsResponseDto" /> class.
        /// </summary>
        /// <param name="platforms">List of distinct platforms (required).</param>
        /// <param name="appVersions">List of distinct app versions (required).</param>
        /// <param name="deviceIds">List of distinct device IDs (required).</param>
        /// <param name="totalSessions">Total session count in the project (required).</param>
        public FilterOptionsResponseDto(List<string> platforms = default(List<string>), List<string> appVersions = default(List<string>), List<string> deviceIds = default(List<string>), decimal totalSessions = default(decimal))
        {
            // to ensure "platforms" is required (not null)
            if (platforms == null)
            {
                throw new ArgumentNullException("platforms is a required property for FilterOptionsResponseDto and cannot be null");
            }
            this.Platforms = platforms;
            // to ensure "appVersions" is required (not null)
            if (appVersions == null)
            {
                throw new ArgumentNullException("appVersions is a required property for FilterOptionsResponseDto and cannot be null");
            }
            this.AppVersions = appVersions;
            // to ensure "deviceIds" is required (not null)
            if (deviceIds == null)
            {
                throw new ArgumentNullException("deviceIds is a required property for FilterOptionsResponseDto and cannot be null");
            }
            this.DeviceIds = deviceIds;
            this.TotalSessions = totalSessions;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// List of distinct platforms
        /// </summary>
        /// <value>List of distinct platforms</value>
        /*
        <example>[&quot;Android&quot;,&quot;iOS&quot;,&quot;Windows&quot;]</example>
        */
        [DataMember(Name = "platforms", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Platforms { get; set; }

        /// <summary>
        /// List of distinct app versions
        /// </summary>
        /// <value>List of distinct app versions</value>
        /*
        <example>[&quot;1.0.0&quot;,&quot;1.1.0&quot;,&quot;2.0.0&quot;]</example>
        */
        [DataMember(Name = "appVersions", IsRequired = true, EmitDefaultValue = true)]
        public List<string> AppVersions { get; set; }

        /// <summary>
        /// List of distinct device IDs
        /// </summary>
        /// <value>List of distinct device IDs</value>
        /*
        <example>[&quot;device-001&quot;,&quot;device-002&quot;]</example>
        */
        [DataMember(Name = "deviceIds", IsRequired = true, EmitDefaultValue = true)]
        public List<string> DeviceIds { get; set; }

        /// <summary>
        /// Total session count in the project
        /// </summary>
        /// <value>Total session count in the project</value>
        /*
        <example>500</example>
        */
        [DataMember(Name = "totalSessions", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalSessions { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FilterOptionsResponseDto {\n");
            sb.Append("  Platforms: ").Append(Platforms).Append("\n");
            sb.Append("  AppVersions: ").Append(AppVersions).Append("\n");
            sb.Append("  DeviceIds: ").Append(DeviceIds).Append("\n");
            sb.Append("  TotalSessions: ").Append(TotalSessions).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
