/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.25.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// GameApiKeyResponseDto
    /// </summary>
    [DataContract(Name = "GameApiKeyResponseDto")]
    public partial class GameApiKeyResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GameApiKeyResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GameApiKeyResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="GameApiKeyResponseDto" /> class.
        /// </summary>
        /// <param name="id">APIキーID (required).</param>
        /// <param name="name">APIキーの識別名 (required).</param>
        /// <param name="isActive">アクティブ状態 (required).</param>
        /// <param name="lastUsedAt">最終使用日時 (required).</param>
        /// <param name="createdAt">作成日時 (required).</param>
        /// <param name="projects">アクセス可能なプロジェクトのリスト (required).</param>
        /// <param name="projectIds">アクセス可能なプロジェクトIDのリスト (deprecated: use projects instead) (required).</param>
        public GameApiKeyResponseDto(string id = default(string), string name = default(string), bool isActive = default(bool), Object lastUsedAt = default(Object), DateTime createdAt = default(DateTime), List<ProjectResponseDto> projects = default(List<ProjectResponseDto>), List<decimal> projectIds = default(List<decimal>))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for GameApiKeyResponseDto and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for GameApiKeyResponseDto and cannot be null");
            }
            this.Name = name;
            this.IsActive = isActive;
            // to ensure "lastUsedAt" is required (not null)
            if (lastUsedAt == null)
            {
                throw new ArgumentNullException("lastUsedAt is a required property for GameApiKeyResponseDto and cannot be null");
            }
            this.LastUsedAt = lastUsedAt;
            this.CreatedAt = createdAt;
            // to ensure "projects" is required (not null)
            if (projects == null)
            {
                throw new ArgumentNullException("projects is a required property for GameApiKeyResponseDto and cannot be null");
            }
            this.Projects = projects;
            // to ensure "projectIds" is required (not null)
            if (projectIds == null)
            {
                throw new ArgumentNullException("projectIds is a required property for GameApiKeyResponseDto and cannot be null");
            }
            this.ProjectIds = projectIds;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// APIキーID
        /// </summary>
        /// <value>APIキーID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// APIキーの識別名
        /// </summary>
        /// <value>APIキーの識別名</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// アクティブ状態
        /// </summary>
        /// <value>アクティブ状態</value>
        [DataMember(Name = "isActive", IsRequired = true, EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// 最終使用日時
        /// </summary>
        /// <value>最終使用日時</value>
        [DataMember(Name = "lastUsedAt", IsRequired = true, EmitDefaultValue = true)]
        public Object LastUsedAt { get; set; }

        /// <summary>
        /// 作成日時
        /// </summary>
        /// <value>作成日時</value>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// アクセス可能なプロジェクトのリスト
        /// </summary>
        /// <value>アクセス可能なプロジェクトのリスト</value>
        [DataMember(Name = "projects", IsRequired = true, EmitDefaultValue = true)]
        public List<ProjectResponseDto> Projects { get; set; }

        /// <summary>
        /// アクセス可能なプロジェクトIDのリスト (deprecated: use projects instead)
        /// </summary>
        /// <value>アクセス可能なプロジェクトIDのリスト (deprecated: use projects instead)</value>
        [DataMember(Name = "projectIds", IsRequired = true, EmitDefaultValue = true)]
        [Obsolete]
        public List<decimal> ProjectIds { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GameApiKeyResponseDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  LastUsedAt: ").Append(LastUsedAt).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Projects: ").Append(Projects).Append("\n");
            sb.Append("  ProjectIds: ").Append(ProjectIds).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
