/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// GetGeneralLogKeysDto
    /// </summary>
    [DataContract(Name = "GetGeneralLogKeysDto")]
    public partial class GetGeneralLogKeysDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetGeneralLogKeysDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetGeneralLogKeysDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetGeneralLogKeysDto" /> class.
        /// </summary>
        /// <param name="keys">List of keys to retrieve (required).</param>
        public GetGeneralLogKeysDto(List<string> keys = default(List<string>))
        {
            // to ensure "keys" is required (not null)
            if (keys == null)
            {
                throw new ArgumentNullException("keys is a required property for GetGeneralLogKeysDto and cannot be null");
            }
            this.Keys = keys;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// List of keys to retrieve
        /// </summary>
        /// <value>List of keys to retrieve</value>
        [DataMember(Name = "keys", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Keys { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetGeneralLogKeysDto {\n");
            sb.Append("  Keys: ").Append(Keys).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
