/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.16.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// GetMapsDto
    /// </summary>
    [DataContract(Name = "GetMapsDto")]
    public partial class GetMapsDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMapsDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMapsDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMapsDto" /> class.
        /// </summary>
        /// <param name="maps">maps (required).</param>
        public GetMapsDto(List<string> maps = default(List<string>))
        {
            // to ensure "maps" is required (not null)
            if (maps == null)
            {
                throw new ArgumentNullException("maps is a required property for GetMapsDto and cannot be null");
            }
            this.Maps = maps;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Maps
        /// </summary>
        [DataMember(Name = "maps", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Maps { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMapsDto {\n");
            sb.Append("  Maps: ").Append(Maps).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
