/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.18.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// GoogleStartQueryDto
    /// </summary>
    [DataContract(Name = "GoogleStartQueryDto")]
    public partial class GoogleStartQueryDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GoogleStartQueryDto" /> class.
        /// </summary>
        /// <param name="state">署名付きのstate（CSRF防止やモード伝播用）。リンク時はAuthControllerが自動生成。.</param>
        public GoogleStartQueryDto(string state = default(string))
        {
            this.State = state;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// 署名付きのstate（CSRF防止やモード伝播用）。リンク時はAuthControllerが自動生成。
        /// </summary>
        /// <value>署名付きのstate（CSRF防止やモード伝播用）。リンク時はAuthControllerが自動生成。</value>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GoogleStartQueryDto {\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
