/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.16.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// GoogleCallbackQueryDto
    /// </summary>
    [DataContract(Name = "GoogleCallbackQueryDto")]
    public partial class GoogleCallbackQueryDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GoogleCallbackQueryDto" /> class.
        /// </summary>
        /// <param name="state">署名付きstate（自前検証用）.</param>
        /// <param name="error">Google側エラー（存在する場合）.</param>
        /// <param name="code">code.</param>
        /// <param name="scope">scope.</param>
        /// <param name="authuser">authuser.</param>
        /// <param name="prompt">prompt.</param>
        /// <param name="hd">hd.</param>
        public GoogleCallbackQueryDto(string state = default(string), string error = default(string), string code = default(string), string scope = default(string), string authuser = default(string), string prompt = default(string), string hd = default(string))
        {
            this.State = state;
            this.Error = error;
            this.Code = code;
            this.Scope = scope;
            this.Authuser = authuser;
            this.Prompt = prompt;
            this.Hd = hd;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// 署名付きstate（自前検証用）
        /// </summary>
        /// <value>署名付きstate（自前検証用）</value>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public string State { get; set; }

        /// <summary>
        /// Google側エラー（存在する場合）
        /// </summary>
        /// <value>Google側エラー（存在する場合）</value>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public string Error { get; set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets Scope
        /// </summary>
        [DataMember(Name = "scope", EmitDefaultValue = false)]
        public string Scope { get; set; }

        /// <summary>
        /// Gets or Sets Authuser
        /// </summary>
        [DataMember(Name = "authuser", EmitDefaultValue = false)]
        public string Authuser { get; set; }

        /// <summary>
        /// Gets or Sets Prompt
        /// </summary>
        [DataMember(Name = "prompt", EmitDefaultValue = false)]
        public string Prompt { get; set; }

        /// <summary>
        /// Gets or Sets Hd
        /// </summary>
        [DataMember(Name = "hd", EmitDefaultValue = false)]
        public string Hd { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GoogleCallbackQueryDto {\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  Authuser: ").Append(Authuser).Append("\n");
            sb.Append("  Prompt: ").Append(Prompt).Append("\n");
            sb.Append("  Hd: ").Append(Hd).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
