/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.27.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// HeatmapTaskDto
    /// </summary>
    [DataContract(Name = "HeatmapTaskDto")]
    public partial class HeatmapTaskDto
    {
        /// <summary>
        /// Status
        /// </summary>
        /// <value>Status</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending = 1,

            /// <summary>
            /// Enum Processing for value: processing
            /// </summary>
            [EnumMember(Value = "processing")]
            Processing = 2,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            [EnumMember(Value = "completed")]
            Completed = 3,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            [EnumMember(Value = "failed")]
            Failed = 4
        }


        /// <summary>
        /// Status
        /// </summary>
        /// <value>Status</value>
        /*
        <example>completed</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapTaskDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HeatmapTaskDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapTaskDto" /> class.
        /// </summary>
        /// <param name="taskId">Task ID (required).</param>
        /// <param name="project">Project (required).</param>
        /// <param name="session">Session.</param>
        /// <param name="sessionIds">Session IDs used for filtering (if multiple sessions).</param>
        /// <param name="searchQuery">Search query text used to filter sessions (GitHub-style query).</param>
        /// <param name="stepSize">Step size (required).</param>
        /// <param name="zVisible">Z visible (required).</param>
        /// <param name="status">Status (required).</param>
        /// <param name="result">Result list.</param>
        /// <param name="createdAt">Created at (required).</param>
        /// <param name="updatedAt">Updated at (required).</param>
        public HeatmapTaskDto(decimal taskId = default(decimal), ProjectResponseDto project = default(ProjectResponseDto), PlaySessionResponseDto session = default(PlaySessionResponseDto), List<decimal> sessionIds = default(List<decimal>), Object searchQuery = default(Object), decimal stepSize = default(decimal), bool zVisible = default(bool), StatusEnum status = default(StatusEnum), List<HeatMapTaskResultListItem> result = default(List<HeatMapTaskResultListItem>), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime))
        {
            this.TaskId = taskId;
            // to ensure "project" is required (not null)
            if (project == null)
            {
                throw new ArgumentNullException("project is a required property for HeatmapTaskDto and cannot be null");
            }
            this.Project = project;
            this.StepSize = stepSize;
            this.ZVisible = zVisible;
            this.Status = status;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Session = session;
            this.SessionIds = sessionIds;
            this.SearchQuery = searchQuery;
            this.Result = result;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Task ID
        /// </summary>
        /// <value>Task ID</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "taskId", IsRequired = true, EmitDefaultValue = true)]
        public decimal TaskId { get; set; }

        /// <summary>
        /// Project
        /// </summary>
        /// <value>Project</value>
        [DataMember(Name = "project", IsRequired = true, EmitDefaultValue = true)]
        public ProjectResponseDto Project { get; set; }

        /// <summary>
        /// Session
        /// </summary>
        /// <value>Session</value>
        [DataMember(Name = "session", EmitDefaultValue = false)]
        public PlaySessionResponseDto Session { get; set; }

        /// <summary>
        /// Session IDs used for filtering (if multiple sessions)
        /// </summary>
        /// <value>Session IDs used for filtering (if multiple sessions)</value>
        /*
        <example>[1,2,3]</example>
        */
        [DataMember(Name = "sessionIds", EmitDefaultValue = true)]
        public List<decimal> SessionIds { get; set; }

        /// <summary>
        /// Search query text used to filter sessions (GitHub-style query)
        /// </summary>
        /// <value>Search query text used to filter sessions (GitHub-style query)</value>
        /*
        <example>platform:Android is:finished</example>
        */
        [DataMember(Name = "searchQuery", EmitDefaultValue = true)]
        public Object SearchQuery { get; set; }

        /// <summary>
        /// Step size
        /// </summary>
        /// <value>Step size</value>
        /*
        <example>200</example>
        */
        [DataMember(Name = "stepSize", IsRequired = true, EmitDefaultValue = true)]
        public decimal StepSize { get; set; }

        /// <summary>
        /// Z visible
        /// </summary>
        /// <value>Z visible</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "zVisible", IsRequired = true, EmitDefaultValue = true)]
        public bool ZVisible { get; set; }

        /// <summary>
        /// Result list
        /// </summary>
        /// <value>Result list</value>
        /*
        <example>[{&quot;x&quot;:0,&quot;y&quot;:0,&quot;z&quot;:0,&quot;density&quot;:0}]</example>
        */
        [DataMember(Name = "result", EmitDefaultValue = true)]
        public List<HeatMapTaskResultListItem> Result { get; set; }

        /// <summary>
        /// Created at
        /// </summary>
        /// <value>Created at</value>
        /*
        <example>2021-01-01T00:00Z</example>
        */
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Updated at
        /// </summary>
        /// <value>Updated at</value>
        /*
        <example>2021-01-01T00:00Z</example>
        */
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HeatmapTaskDto {\n");
            sb.Append("  TaskId: ").Append(TaskId).Append("\n");
            sb.Append("  Project: ").Append(Project).Append("\n");
            sb.Append("  Session: ").Append(Session).Append("\n");
            sb.Append("  SessionIds: ").Append(SessionIds).Append("\n");
            sb.Append("  SearchQuery: ").Append(SearchQuery).Append("\n");
            sb.Append("  StepSize: ").Append(StepSize).Append("\n");
            sb.Append("  ZVisible: ").Append(ZVisible).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
