/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.24.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// HeatmapEmbedUrlResponseDto
    /// </summary>
    [DataContract(Name = "HeatmapEmbedUrlResponseDto")]
    public partial class HeatmapEmbedUrlResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapEmbedUrlResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HeatmapEmbedUrlResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapEmbedUrlResponseDto" /> class.
        /// </summary>
        /// <param name="url">ヒートマップ埋め込みページのURL（トークン付き） (required).</param>
        /// <param name="expiresAt">トークンの有効期限（ISO 8601形式） (required).</param>
        public HeatmapEmbedUrlResponseDto(string url = default(string), string expiresAt = default(string))
        {
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for HeatmapEmbedUrlResponseDto and cannot be null");
            }
            this.Url = url;
            // to ensure "expiresAt" is required (not null)
            if (expiresAt == null)
            {
                throw new ArgumentNullException("expiresAt is a required property for HeatmapEmbedUrlResponseDto and cannot be null");
            }
            this.ExpiresAt = expiresAt;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// ヒートマップ埋め込みページのURL（トークン付き）
        /// </summary>
        /// <value>ヒートマップ埋め込みページのURL（トークン付き）</value>
        /*
        <example>https://ludiscan.com/heatmap/embed/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...</example>
        */
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// トークンの有効期限（ISO 8601形式）
        /// </summary>
        /// <value>トークンの有効期限（ISO 8601形式）</value>
        /*
        <example>2024-01-01T12:00:00.000Z</example>
        */
        [DataMember(Name = "expiresAt", IsRequired = true, EmitDefaultValue = true)]
        public string ExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HeatmapEmbedUrlResponseDto {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
