/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.25.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// HeatmapSearchQueryDto
    /// </summary>
    [DataContract(Name = "HeatmapSearchQueryDto")]
    public partial class HeatmapSearchQueryDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapSearchQueryDto" /> class.
        /// </summary>
        /// <param name="q">Unified search query (plain text keyword OR GitHub-style filters).</param>
        /// <param name="name">Session name (partial match).</param>
        /// <param name="deviceId">Device ID (exact match).</param>
        /// <param name="platform">Platform (exact match).</param>
        /// <param name="appVersion">App version (exact match).</param>
        /// <param name="startTimeFrom">Start time from (ISO 8601).</param>
        /// <param name="startTimeTo">Start time to (ISO 8601).</param>
        /// <param name="endTimeFrom">End time from (ISO 8601).</param>
        /// <param name="endTimeTo">End time to (ISO 8601).</param>
        /// <param name="isPlaying">Filter by playing status (true: currently playing, false: finished).</param>
        /// <param name="metadataKey">Metadata key to search for.</param>
        /// <param name="metadataValue">Metadata value to search for (requires metadata_key).</param>
        public HeatmapSearchQueryDto(string q = default(string), string name = default(string), string deviceId = default(string), string platform = default(string), string appVersion = default(string), string startTimeFrom = default(string), string startTimeTo = default(string), string endTimeFrom = default(string), string endTimeTo = default(string), bool isPlaying = default(bool), string metadataKey = default(string), string metadataValue = default(string))
        {
            this.Q = q;
            this.Name = name;
            this.DeviceId = deviceId;
            this.Platform = platform;
            this.AppVersion = appVersion;
            this.StartTimeFrom = startTimeFrom;
            this.StartTimeTo = startTimeTo;
            this.EndTimeFrom = endTimeFrom;
            this.EndTimeTo = endTimeTo;
            this.IsPlaying = isPlaying;
            this.MetadataKey = metadataKey;
            this.MetadataValue = metadataValue;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Unified search query (plain text keyword OR GitHub-style filters)
        /// </summary>
        /// <value>Unified search query (plain text keyword OR GitHub-style filters)</value>
        /*
        <example>platform:Android is:finished</example>
        */
        [DataMember(Name = "q", EmitDefaultValue = false)]
        public string Q { get; set; }

        /// <summary>
        /// Session name (partial match)
        /// </summary>
        /// <value>Session name (partial match)</value>
        /*
        <example>Session_2025</example>
        */
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Device ID (exact match)
        /// </summary>
        /// <value>Device ID (exact match)</value>
        /*
        <example>device-123</example>
        */
        [DataMember(Name = "device_id", EmitDefaultValue = false)]
        public string DeviceId { get; set; }

        /// <summary>
        /// Platform (exact match)
        /// </summary>
        /// <value>Platform (exact match)</value>
        /*
        <example>Android</example>
        */
        [DataMember(Name = "platform", EmitDefaultValue = false)]
        public string Platform { get; set; }

        /// <summary>
        /// App version (exact match)
        /// </summary>
        /// <value>App version (exact match)</value>
        /*
        <example>1.0.0</example>
        */
        [DataMember(Name = "app_version", EmitDefaultValue = false)]
        public string AppVersion { get; set; }

        /// <summary>
        /// Start time from (ISO 8601)
        /// </summary>
        /// <value>Start time from (ISO 8601)</value>
        /*
        <example>2025-01-01T00:00:00Z</example>
        */
        [DataMember(Name = "start_time_from", EmitDefaultValue = false)]
        public string StartTimeFrom { get; set; }

        /// <summary>
        /// Start time to (ISO 8601)
        /// </summary>
        /// <value>Start time to (ISO 8601)</value>
        /*
        <example>2025-01-31T23:59:59Z</example>
        */
        [DataMember(Name = "start_time_to", EmitDefaultValue = false)]
        public string StartTimeTo { get; set; }

        /// <summary>
        /// End time from (ISO 8601)
        /// </summary>
        /// <value>End time from (ISO 8601)</value>
        /*
        <example>2025-01-01T00:00:00Z</example>
        */
        [DataMember(Name = "end_time_from", EmitDefaultValue = false)]
        public string EndTimeFrom { get; set; }

        /// <summary>
        /// End time to (ISO 8601)
        /// </summary>
        /// <value>End time to (ISO 8601)</value>
        /*
        <example>2025-01-31T23:59:59Z</example>
        */
        [DataMember(Name = "end_time_to", EmitDefaultValue = false)]
        public string EndTimeTo { get; set; }

        /// <summary>
        /// Filter by playing status (true: currently playing, false: finished)
        /// </summary>
        /// <value>Filter by playing status (true: currently playing, false: finished)</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "is_playing", EmitDefaultValue = true)]
        public bool IsPlaying { get; set; }

        /// <summary>
        /// Metadata key to search for
        /// </summary>
        /// <value>Metadata key to search for</value>
        /*
        <example>mapName</example>
        */
        [DataMember(Name = "metadata_key", EmitDefaultValue = false)]
        public string MetadataKey { get; set; }

        /// <summary>
        /// Metadata value to search for (requires metadata_key)
        /// </summary>
        /// <value>Metadata value to search for (requires metadata_key)</value>
        /*
        <example>Level1</example>
        */
        [DataMember(Name = "metadata_value", EmitDefaultValue = false)]
        public string MetadataValue { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HeatmapSearchQueryDto {\n");
            sb.Append("  Q: ").Append(Q).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DeviceId: ").Append(DeviceId).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  AppVersion: ").Append(AppVersion).Append("\n");
            sb.Append("  StartTimeFrom: ").Append(StartTimeFrom).Append("\n");
            sb.Append("  StartTimeTo: ").Append(StartTimeTo).Append("\n");
            sb.Append("  EndTimeFrom: ").Append(EndTimeFrom).Append("\n");
            sb.Append("  EndTimeTo: ").Append(EndTimeTo).Append("\n");
            sb.Append("  IsPlaying: ").Append(IsPlaying).Append("\n");
            sb.Append("  MetadataKey: ").Append(MetadataKey).Append("\n");
            sb.Append("  MetadataValue: ").Append(MetadataValue).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
