/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.33.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// HeatmapTaskListDto
    /// </summary>
    [DataContract(Name = "HeatmapTaskListDto")]
    public partial class HeatmapTaskListDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapTaskListDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HeatmapTaskListDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapTaskListDto" /> class.
        /// </summary>
        /// <param name="tasks">Tasks list (required).</param>
        /// <param name="total">Total count (required).</param>
        /// <param name="limit">Limit (required).</param>
        /// <param name="offset">Offset (required).</param>
        public HeatmapTaskListDto(List<HeatmapTaskListItemDto> tasks = default(List<HeatmapTaskListItemDto>), decimal total = default(decimal), decimal limit = default(decimal), decimal offset = default(decimal))
        {
            // to ensure "tasks" is required (not null)
            if (tasks == null)
            {
                throw new ArgumentNullException("tasks is a required property for HeatmapTaskListDto and cannot be null");
            }
            this.Tasks = tasks;
            this.Total = total;
            this.Limit = limit;
            this.Offset = offset;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Tasks list
        /// </summary>
        /// <value>Tasks list</value>
        [DataMember(Name = "tasks", IsRequired = true, EmitDefaultValue = true)]
        public List<HeatmapTaskListItemDto> Tasks { get; set; }

        /// <summary>
        /// Total count
        /// </summary>
        /// <value>Total count</value>
        /*
        <example>100</example>
        */
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public decimal Total { get; set; }

        /// <summary>
        /// Limit
        /// </summary>
        /// <value>Limit</value>
        /*
        <example>20</example>
        */
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public decimal Limit { get; set; }

        /// <summary>
        /// Offset
        /// </summary>
        /// <value>Offset</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "offset", IsRequired = true, EmitDefaultValue = true)]
        public decimal Offset { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HeatmapTaskListDto {\n");
            sb.Append("  Tasks: ").Append(Tasks).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
