/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// HeatmapTaskV01Dto
    /// </summary>
    [DataContract(Name = "HeatmapTaskV01Dto")]
    public partial class HeatmapTaskV01Dto
    {
        /// <summary>
        /// Task status
        /// </summary>
        /// <value>Task status</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending = 1,

            /// <summary>
            /// Enum Processing for value: processing
            /// </summary>
            [EnumMember(Value = "processing")]
            Processing = 2,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            [EnumMember(Value = "completed")]
            Completed = 3,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            [EnumMember(Value = "failed")]
            Failed = 4
        }


        /// <summary>
        /// Task status
        /// </summary>
        /// <value>Task status</value>
        /*
        <example>completed</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapTaskV01Dto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HeatmapTaskV01Dto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapTaskV01Dto" /> class.
        /// </summary>
        /// <param name="taskId">Task ID (required).</param>
        /// <param name="project">Project (required).</param>
        /// <param name="session">Session (if task is for a specific session).</param>
        /// <param name="sessionIds">Session IDs used for filtering (if multiple sessions).</param>
        /// <param name="searchQuery">Search query text used to filter sessions (GitHub-style query).</param>
        /// <param name="stepSize">Step size for grid cells (required).</param>
        /// <param name="zVisible">Whether Z axis is visible (3D mode) (required).</param>
        /// <param name="status">Task status (required).</param>
        /// <param name="result">Normalized heatmap result with density values in 0-1 range (required).</param>
        /// <param name="stats">Normalization statistics (required).</param>
        /// <param name="createdAt">Created at timestamp (required).</param>
        /// <param name="updatedAt">Updated at timestamp (required).</param>
        public HeatmapTaskV01Dto(decimal taskId = default(decimal), ProjectResponseDto project = default(ProjectResponseDto), PlaySessionResponseDto session = default(PlaySessionResponseDto), List<decimal> sessionIds = default(List<decimal>), Object searchQuery = default(Object), decimal stepSize = default(decimal), bool zVisible = default(bool), StatusEnum status = default(StatusEnum), List<NormalizedHeatmapPointDto> result = default(List<NormalizedHeatmapPointDto>), NormalizedHeatmapStatsDto stats = default(NormalizedHeatmapStatsDto), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime))
        {
            this.TaskId = taskId;
            // to ensure "project" is required (not null)
            if (project == null)
            {
                throw new ArgumentNullException("project is a required property for HeatmapTaskV01Dto and cannot be null");
            }
            this.Project = project;
            this.StepSize = stepSize;
            this.ZVisible = zVisible;
            this.Status = status;
            // to ensure "result" is required (not null)
            if (result == null)
            {
                throw new ArgumentNullException("result is a required property for HeatmapTaskV01Dto and cannot be null");
            }
            this.Result = result;
            // to ensure "stats" is required (not null)
            if (stats == null)
            {
                throw new ArgumentNullException("stats is a required property for HeatmapTaskV01Dto and cannot be null");
            }
            this.Stats = stats;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Session = session;
            this.SessionIds = sessionIds;
            this.SearchQuery = searchQuery;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Task ID
        /// </summary>
        /// <value>Task ID</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "taskId", IsRequired = true, EmitDefaultValue = true)]
        public decimal TaskId { get; set; }

        /// <summary>
        /// Project
        /// </summary>
        /// <value>Project</value>
        [DataMember(Name = "project", IsRequired = true, EmitDefaultValue = true)]
        public ProjectResponseDto Project { get; set; }

        /// <summary>
        /// Session (if task is for a specific session)
        /// </summary>
        /// <value>Session (if task is for a specific session)</value>
        [DataMember(Name = "session", EmitDefaultValue = true)]
        public PlaySessionResponseDto Session { get; set; }

        /// <summary>
        /// Session IDs used for filtering (if multiple sessions)
        /// </summary>
        /// <value>Session IDs used for filtering (if multiple sessions)</value>
        /*
        <example>[1,2,3]</example>
        */
        [DataMember(Name = "sessionIds", EmitDefaultValue = true)]
        public List<decimal> SessionIds { get; set; }

        /// <summary>
        /// Search query text used to filter sessions (GitHub-style query)
        /// </summary>
        /// <value>Search query text used to filter sessions (GitHub-style query)</value>
        /*
        <example>platform:Android is:finished</example>
        */
        [DataMember(Name = "searchQuery", EmitDefaultValue = true)]
        public Object SearchQuery { get; set; }

        /// <summary>
        /// Step size for grid cells
        /// </summary>
        /// <value>Step size for grid cells</value>
        /*
        <example>200</example>
        */
        [DataMember(Name = "stepSize", IsRequired = true, EmitDefaultValue = true)]
        public decimal StepSize { get; set; }

        /// <summary>
        /// Whether Z axis is visible (3D mode)
        /// </summary>
        /// <value>Whether Z axis is visible (3D mode)</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "zVisible", IsRequired = true, EmitDefaultValue = true)]
        public bool ZVisible { get; set; }

        /// <summary>
        /// Normalized heatmap result with density values in 0-1 range
        /// </summary>
        /// <value>Normalized heatmap result with density values in 0-1 range</value>
        [DataMember(Name = "result", IsRequired = true, EmitDefaultValue = true)]
        public List<NormalizedHeatmapPointDto> Result { get; set; }

        /// <summary>
        /// Normalization statistics
        /// </summary>
        /// <value>Normalization statistics</value>
        [DataMember(Name = "stats", IsRequired = true, EmitDefaultValue = true)]
        public NormalizedHeatmapStatsDto Stats { get; set; }

        /// <summary>
        /// Created at timestamp
        /// </summary>
        /// <value>Created at timestamp</value>
        /*
        <example>2021-01-01T00:00Z</example>
        */
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Updated at timestamp
        /// </summary>
        /// <value>Updated at timestamp</value>
        /*
        <example>2021-01-01T00:00Z</example>
        */
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HeatmapTaskV01Dto {\n");
            sb.Append("  TaskId: ").Append(TaskId).Append("\n");
            sb.Append("  Project: ").Append(Project).Append("\n");
            sb.Append("  Session: ").Append(Session).Append("\n");
            sb.Append("  SessionIds: ").Append(SessionIds).Append("\n");
            sb.Append("  SearchQuery: ").Append(SearchQuery).Append("\n");
            sb.Append("  StepSize: ").Append(StepSize).Append("\n");
            sb.Append("  ZVisible: ").Append(ZVisible).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  Stats: ").Append(Stats).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
