/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.26.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// HeatmapTaskV01ListResponseDto
    /// </summary>
    [DataContract(Name = "HeatmapTaskV01ListResponseDto")]
    public partial class HeatmapTaskV01ListResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapTaskV01ListResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HeatmapTaskV01ListResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapTaskV01ListResponseDto" /> class.
        /// </summary>
        /// <param name="tasks">List of heatmap tasks (required).</param>
        /// <param name="total">Total number of tasks (required).</param>
        /// <param name="limit">Number of tasks returned (required).</param>
        /// <param name="offset">Offset for pagination (required).</param>
        public HeatmapTaskV01ListResponseDto(List<HeatmapTaskV01ListItemDto> tasks = default(List<HeatmapTaskV01ListItemDto>), decimal total = default(decimal), decimal limit = default(decimal), decimal offset = default(decimal))
        {
            // to ensure "tasks" is required (not null)
            if (tasks == null)
            {
                throw new ArgumentNullException("tasks is a required property for HeatmapTaskV01ListResponseDto and cannot be null");
            }
            this.Tasks = tasks;
            this.Total = total;
            this.Limit = limit;
            this.Offset = offset;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// List of heatmap tasks
        /// </summary>
        /// <value>List of heatmap tasks</value>
        [DataMember(Name = "tasks", IsRequired = true, EmitDefaultValue = true)]
        public List<HeatmapTaskV01ListItemDto> Tasks { get; set; }

        /// <summary>
        /// Total number of tasks
        /// </summary>
        /// <value>Total number of tasks</value>
        /*
        <example>100</example>
        */
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public decimal Total { get; set; }

        /// <summary>
        /// Number of tasks returned
        /// </summary>
        /// <value>Number of tasks returned</value>
        /*
        <example>20</example>
        */
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public decimal Limit { get; set; }

        /// <summary>
        /// Offset for pagination
        /// </summary>
        /// <value>Offset for pagination</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "offset", IsRequired = true, EmitDefaultValue = true)]
        public decimal Offset { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HeatmapTaskV01ListResponseDto {\n");
            sb.Append("  Tasks: ").Append(Tasks).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
