/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.19.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// HeatMapTaskResultListItem
    /// </summary>
    [DataContract(Name = "HeatMapTaskResultListItem")]
    public partial class HeatMapTaskResultListItem
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatMapTaskResultListItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HeatMapTaskResultListItem()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatMapTaskResultListItem" /> class.
        /// </summary>
        /// <param name="x">X (required).</param>
        /// <param name="y">Y (required).</param>
        /// <param name="z">Z.</param>
        /// <param name="density">Density (required).</param>
        public HeatMapTaskResultListItem(decimal x = default(decimal), decimal y = default(decimal), decimal z = default(decimal), decimal density = default(decimal))
        {
            this.X = x;
            this.Y = y;
            this.Density = density;
            this.Z = z;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// X
        /// </summary>
        /// <value>X</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "x", IsRequired = true, EmitDefaultValue = true)]
        public decimal X { get; set; }

        /// <summary>
        /// Y
        /// </summary>
        /// <value>Y</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "y", IsRequired = true, EmitDefaultValue = true)]
        public decimal Y { get; set; }

        /// <summary>
        /// Z
        /// </summary>
        /// <value>Z</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "z", EmitDefaultValue = false)]
        public decimal Z { get; set; }

        /// <summary>
        /// Density
        /// </summary>
        /// <value>Density</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "density", IsRequired = true, EmitDefaultValue = true)]
        public decimal Density { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HeatMapTaskResultListItem {\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Z: ").Append(Z).Append("\n");
            sb.Append("  Density: ").Append(Density).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
