/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.32.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// HeatmapTaskV01ListItemDto
    /// </summary>
    [DataContract(Name = "HeatmapTaskV01ListItemDto")]
    public partial class HeatmapTaskV01ListItemDto
    {
        /// <summary>
        /// Task status
        /// </summary>
        /// <value>Task status</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending = 1,

            /// <summary>
            /// Enum Processing for value: processing
            /// </summary>
            [EnumMember(Value = "processing")]
            Processing = 2,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            [EnumMember(Value = "completed")]
            Completed = 3,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            [EnumMember(Value = "failed")]
            Failed = 4
        }


        /// <summary>
        /// Task status
        /// </summary>
        /// <value>Task status</value>
        /*
        <example>completed</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapTaskV01ListItemDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HeatmapTaskV01ListItemDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatmapTaskV01ListItemDto" /> class.
        /// </summary>
        /// <param name="taskId">Task ID (required).</param>
        /// <param name="sessionId">Session ID (if task is for a specific session).</param>
        /// <param name="sessionIds">Session IDs used for filtering (if multiple sessions).</param>
        /// <param name="searchQuery">Search query text used to filter sessions.</param>
        /// <param name="stepSize">Step size for grid cells (required).</param>
        /// <param name="zVisible">Whether Z axis is visible (3D mode) (required).</param>
        /// <param name="status">Task status (required).</param>
        /// <param name="createdAt">Created at timestamp (required).</param>
        /// <param name="updatedAt">Updated at timestamp (required).</param>
        public HeatmapTaskV01ListItemDto(decimal taskId = default(decimal), Object sessionId = default(Object), List<decimal> sessionIds = default(List<decimal>), Object searchQuery = default(Object), decimal stepSize = default(decimal), bool zVisible = default(bool), StatusEnum status = default(StatusEnum), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime))
        {
            this.TaskId = taskId;
            this.StepSize = stepSize;
            this.ZVisible = zVisible;
            this.Status = status;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.SessionId = sessionId;
            this.SessionIds = sessionIds;
            this.SearchQuery = searchQuery;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Task ID
        /// </summary>
        /// <value>Task ID</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "taskId", IsRequired = true, EmitDefaultValue = true)]
        public decimal TaskId { get; set; }

        /// <summary>
        /// Session ID (if task is for a specific session)
        /// </summary>
        /// <value>Session ID (if task is for a specific session)</value>
        /*
        <example>123</example>
        */
        [DataMember(Name = "sessionId", EmitDefaultValue = true)]
        public Object SessionId { get; set; }

        /// <summary>
        /// Session IDs used for filtering (if multiple sessions)
        /// </summary>
        /// <value>Session IDs used for filtering (if multiple sessions)</value>
        /*
        <example>[1,2,3]</example>
        */
        [DataMember(Name = "sessionIds", EmitDefaultValue = true)]
        public List<decimal> SessionIds { get; set; }

        /// <summary>
        /// Search query text used to filter sessions
        /// </summary>
        /// <value>Search query text used to filter sessions</value>
        /*
        <example>platform:Android is:finished</example>
        */
        [DataMember(Name = "searchQuery", EmitDefaultValue = true)]
        public Object SearchQuery { get; set; }

        /// <summary>
        /// Step size for grid cells
        /// </summary>
        /// <value>Step size for grid cells</value>
        /*
        <example>200</example>
        */
        [DataMember(Name = "stepSize", IsRequired = true, EmitDefaultValue = true)]
        public decimal StepSize { get; set; }

        /// <summary>
        /// Whether Z axis is visible (3D mode)
        /// </summary>
        /// <value>Whether Z axis is visible (3D mode)</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "zVisible", IsRequired = true, EmitDefaultValue = true)]
        public bool ZVisible { get; set; }

        /// <summary>
        /// Created at timestamp
        /// </summary>
        /// <value>Created at timestamp</value>
        /*
        <example>2021-01-01T00:00Z</example>
        */
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Updated at timestamp
        /// </summary>
        /// <value>Updated at timestamp</value>
        /*
        <example>2021-01-01T00:00Z</example>
        */
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HeatmapTaskV01ListItemDto {\n");
            sb.Append("  TaskId: ").Append(TaskId).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  SessionIds: ").Append(SessionIds).Append("\n");
            sb.Append("  SearchQuery: ").Append(SearchQuery).Append("\n");
            sb.Append("  StepSize: ").Append(StepSize).Append("\n");
            sb.Append("  ZVisible: ").Append(ZVisible).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
