/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.31.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// ImprovementRouteDto
    /// </summary>
    [DataContract(Name = "ImprovementRouteDto")]
    public partial class ImprovementRouteDto
    {
        /// <summary>
        /// Type of improvement strategy
        /// </summary>
        /// <value>Type of improvement strategy</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StrategyTypeEnum
        {
            /// <summary>
            /// Enum Divergence for value: divergence
            /// </summary>
            [EnumMember(Value = "divergence")]
            Divergence = 1,

            /// <summary>
            /// Enum SafetyPassage for value: safety_passage
            /// </summary>
            [EnumMember(Value = "safety_passage")]
            SafetyPassage = 2,

            /// <summary>
            /// Enum Faster for value: faster
            /// </summary>
            [EnumMember(Value = "faster")]
            Faster = 3
        }


        /// <summary>
        /// Type of improvement strategy
        /// </summary>
        /// <value>Type of improvement strategy</value>
        [DataMember(Name = "strategy_type", IsRequired = true, EmitDefaultValue = true)]
        public StrategyTypeEnum StrategyType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImprovementRouteDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ImprovementRouteDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImprovementRouteDto" /> class.
        /// </summary>
        /// <param name="id">Improvement route ID (required).</param>
        /// <param name="strategyType">Type of improvement strategy (required).</param>
        /// <param name="trajectoryPoints">Recommended trajectory points (required).</param>
        /// <param name="successRate">Success rate (0-1).</param>
        /// <param name="successCount">Number of times this route succeeded.</param>
        /// <param name="avgDurationMs">Average duration in milliseconds.</param>
        /// <param name="timeSavedMs">Time saved compared to death routes (milliseconds).</param>
        /// <param name="divergenceAnalysis">Analysis for divergence strategy.</param>
        /// <param name="safetyScore">Safety score (0-1) for safety_passage strategy.</param>
        /// <param name="evidence">Evidence supporting the improvement.</param>
        /// <param name="reasoning">Reasoning behind the improvement.</param>
        /// <param name="feedbackTotalCount">Total feedback count (required).</param>
        /// <param name="feedbackAvgRating">Average feedback rating (1-3) (required).</param>
        public ImprovementRouteDto(decimal id = default(decimal), StrategyTypeEnum strategyType = default(StrategyTypeEnum), List<RawRouteDtoTrajectoryPointsInner> trajectoryPoints = default(List<RawRouteDtoTrajectoryPointsInner>), decimal successRate = default(decimal), int successCount = default(int), int avgDurationMs = default(int), int timeSavedMs = default(int), Dictionary<string, Object> divergenceAnalysis = default(Dictionary<string, Object>), decimal safetyScore = default(decimal), Dictionary<string, Object> evidence = default(Dictionary<string, Object>), string reasoning = default(string), decimal feedbackTotalCount = default(decimal), decimal feedbackAvgRating = default(decimal))
        {
            this.Id = id;
            this.StrategyType = strategyType;
            // to ensure "trajectoryPoints" is required (not null)
            if (trajectoryPoints == null)
            {
                throw new ArgumentNullException("trajectoryPoints is a required property for ImprovementRouteDto and cannot be null");
            }
            this.TrajectoryPoints = trajectoryPoints;
            this.FeedbackTotalCount = feedbackTotalCount;
            this.FeedbackAvgRating = feedbackAvgRating;
            this.SuccessRate = successRate;
            this.SuccessCount = successCount;
            this.AvgDurationMs = avgDurationMs;
            this.TimeSavedMs = timeSavedMs;
            this.DivergenceAnalysis = divergenceAnalysis;
            this.SafetyScore = safetyScore;
            this.Evidence = evidence;
            this.Reasoning = reasoning;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Improvement route ID
        /// </summary>
        /// <value>Improvement route ID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public decimal Id { get; set; }

        /// <summary>
        /// Recommended trajectory points
        /// </summary>
        /// <value>Recommended trajectory points</value>
        [DataMember(Name = "trajectory_points", IsRequired = true, EmitDefaultValue = true)]
        public List<RawRouteDtoTrajectoryPointsInner> TrajectoryPoints { get; set; }

        /// <summary>
        /// Success rate (0-1)
        /// </summary>
        /// <value>Success rate (0-1)</value>
        [DataMember(Name = "success_rate", EmitDefaultValue = false)]
        public decimal SuccessRate { get; set; }

        /// <summary>
        /// Number of times this route succeeded
        /// </summary>
        /// <value>Number of times this route succeeded</value>
        [DataMember(Name = "success_count", EmitDefaultValue = false)]
        public int SuccessCount { get; set; }

        /// <summary>
        /// Average duration in milliseconds
        /// </summary>
        /// <value>Average duration in milliseconds</value>
        [DataMember(Name = "avg_duration_ms", EmitDefaultValue = false)]
        public int AvgDurationMs { get; set; }

        /// <summary>
        /// Time saved compared to death routes (milliseconds)
        /// </summary>
        /// <value>Time saved compared to death routes (milliseconds)</value>
        [DataMember(Name = "time_saved_ms", EmitDefaultValue = false)]
        public int TimeSavedMs { get; set; }

        /// <summary>
        /// Analysis for divergence strategy
        /// </summary>
        /// <value>Analysis for divergence strategy</value>
        /*
        <example>{&quot;divergence_point&quot;:{&quot;x&quot;:100,&quot;y&quot;:200,&quot;z&quot;:0},&quot;distance_to_event_cluster&quot;:15.5,&quot;common_prefix_length&quot;:10}</example>
        */
        [DataMember(Name = "divergence_analysis", EmitDefaultValue = false)]
        public Dictionary<string, Object> DivergenceAnalysis { get; set; }

        /// <summary>
        /// Safety score (0-1) for safety_passage strategy
        /// </summary>
        /// <value>Safety score (0-1) for safety_passage strategy</value>
        [DataMember(Name = "safety_score", EmitDefaultValue = false)]
        public decimal SafetyScore { get; set; }

        /// <summary>
        /// Evidence supporting the improvement
        /// </summary>
        /// <value>Evidence supporting the improvement</value>
        /*
        <example>{&quot;description&quot;:&quot;Based on successful player routes&quot;,&quot;reference_player_count&quot;:5,&quot;data_source&quot;:&quot;success_route&quot;,&quot;confidence&quot;:&quot;high&quot;}</example>
        */
        [DataMember(Name = "evidence", EmitDefaultValue = false)]
        public Dictionary<string, Object> Evidence { get; set; }

        /// <summary>
        /// Reasoning behind the improvement
        /// </summary>
        /// <value>Reasoning behind the improvement</value>
        [DataMember(Name = "reasoning", EmitDefaultValue = false)]
        public string Reasoning { get; set; }

        /// <summary>
        /// Total feedback count
        /// </summary>
        /// <value>Total feedback count</value>
        [DataMember(Name = "feedback_total_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal FeedbackTotalCount { get; set; }

        /// <summary>
        /// Average feedback rating (1-3)
        /// </summary>
        /// <value>Average feedback rating (1-3)</value>
        [DataMember(Name = "feedback_avg_rating", IsRequired = true, EmitDefaultValue = true)]
        public decimal FeedbackAvgRating { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImprovementRouteDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  StrategyType: ").Append(StrategyType).Append("\n");
            sb.Append("  TrajectoryPoints: ").Append(TrajectoryPoints).Append("\n");
            sb.Append("  SuccessRate: ").Append(SuccessRate).Append("\n");
            sb.Append("  SuccessCount: ").Append(SuccessCount).Append("\n");
            sb.Append("  AvgDurationMs: ").Append(AvgDurationMs).Append("\n");
            sb.Append("  TimeSavedMs: ").Append(TimeSavedMs).Append("\n");
            sb.Append("  DivergenceAnalysis: ").Append(DivergenceAnalysis).Append("\n");
            sb.Append("  SafetyScore: ").Append(SafetyScore).Append("\n");
            sb.Append("  Evidence: ").Append(Evidence).Append("\n");
            sb.Append("  Reasoning: ").Append(Reasoning).Append("\n");
            sb.Append("  FeedbackTotalCount: ").Append(FeedbackTotalCount).Append("\n");
            sb.Append("  FeedbackAvgRating: ").Append(FeedbackAvgRating).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
