/*
 * API Documentation
 *
 * The API description
 *
 * The version of the OpenAPI document: 1.13.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// ImprovementRouteFeedbackRecordDto
    /// </summary>
    [DataContract(Name = "ImprovementRouteFeedbackRecordDto")]
    public partial class ImprovementRouteFeedbackRecordDto
    {
        /// <summary>
        /// Rating: 1&#x3D;Bad, 2&#x3D;Neutral, 3&#x3D;Good
        /// </summary>
        /// <value>Rating: 1&#x3D;Bad, 2&#x3D;Neutral, 3&#x3D;Good</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RatingEnum
        {
            /// <summary>
            /// Enum _1 for value: 1
            /// </summary>
            [EnumMember(Value = "1")]
            _1 = 1,

            /// <summary>
            /// Enum _2 for value: 2
            /// </summary>
            [EnumMember(Value = "2")]
            _2 = 2,

            /// <summary>
            /// Enum _3 for value: 3
            /// </summary>
            [EnumMember(Value = "3")]
            _3 = 3
        }


        /// <summary>
        /// Rating: 1&#x3D;Bad, 2&#x3D;Neutral, 3&#x3D;Good
        /// </summary>
        /// <value>Rating: 1&#x3D;Bad, 2&#x3D;Neutral, 3&#x3D;Good</value>
        [DataMember(Name = "rating", IsRequired = true, EmitDefaultValue = true)]
        public RatingEnum Rating { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImprovementRouteFeedbackRecordDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ImprovementRouteFeedbackRecordDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImprovementRouteFeedbackRecordDto" /> class.
        /// </summary>
        /// <param name="id">Feedback ID (required).</param>
        /// <param name="playerId">Player ID who gave the feedback (required).</param>
        /// <param name="rating">Rating: 1&#x3D;Bad, 2&#x3D;Neutral, 3&#x3D;Good (required).</param>
        /// <param name="comment">Comment from the player.</param>
        /// <param name="createdAt">Feedback submission timestamp (required).</param>
        public ImprovementRouteFeedbackRecordDto(decimal id = default(decimal), string playerId = default(string), RatingEnum rating = default(RatingEnum), string comment = default(string), DateTime createdAt = default(DateTime))
        {
            this.Id = id;
            // to ensure "playerId" is required (not null)
            if (playerId == null)
            {
                throw new ArgumentNullException("playerId is a required property for ImprovementRouteFeedbackRecordDto and cannot be null");
            }
            this.PlayerId = playerId;
            this.Rating = rating;
            this.CreatedAt = createdAt;
            this.Comment = comment;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Feedback ID
        /// </summary>
        /// <value>Feedback ID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public decimal Id { get; set; }

        /// <summary>
        /// Player ID who gave the feedback
        /// </summary>
        /// <value>Player ID who gave the feedback</value>
        [DataMember(Name = "player_id", IsRequired = true, EmitDefaultValue = true)]
        public string PlayerId { get; set; }

        /// <summary>
        /// Comment from the player
        /// </summary>
        /// <value>Comment from the player</value>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// Feedback submission timestamp
        /// </summary>
        /// <value>Feedback submission timestamp</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImprovementRouteFeedbackRecordDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PlayerId: ").Append(PlayerId).Append("\n");
            sb.Append("  Rating: ").Append(Rating).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
