/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// MetadataKeyInfoDto
    /// </summary>
    [DataContract(Name = "MetadataKeyInfoDto")]
    public partial class MetadataKeyInfoDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetadataKeyInfoDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MetadataKeyInfoDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="MetadataKeyInfoDto" /> class.
        /// </summary>
        /// <param name="key">Metadata key name (required).</param>
        /// <param name="count">Number of sessions that have this key (required).</param>
        /// <param name="isNumeric">Whether the values are numeric (can be aggregated) (required).</param>
        /// <param name="sampleValues">Sample values (up to 5) (required).</param>
        public MetadataKeyInfoDto(string key = default(string), decimal count = default(decimal), bool isNumeric = default(bool), List<string> sampleValues = default(List<string>))
        {
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for MetadataKeyInfoDto and cannot be null");
            }
            this.Key = key;
            this.Count = count;
            this.IsNumeric = isNumeric;
            // to ensure "sampleValues" is required (not null)
            if (sampleValues == null)
            {
                throw new ArgumentNullException("sampleValues is a required property for MetadataKeyInfoDto and cannot be null");
            }
            this.SampleValues = sampleValues;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Metadata key name
        /// </summary>
        /// <value>Metadata key name</value>
        /*
        <example>score</example>
        */
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Number of sessions that have this key
        /// </summary>
        /// <value>Number of sessions that have this key</value>
        /*
        <example>150</example>
        */
        [DataMember(Name = "count", IsRequired = true, EmitDefaultValue = true)]
        public decimal Count { get; set; }

        /// <summary>
        /// Whether the values are numeric (can be aggregated)
        /// </summary>
        /// <value>Whether the values are numeric (can be aggregated)</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isNumeric", IsRequired = true, EmitDefaultValue = true)]
        public bool IsNumeric { get; set; }

        /// <summary>
        /// Sample values (up to 5)
        /// </summary>
        /// <value>Sample values (up to 5)</value>
        /*
        <example>[100,200,150]</example>
        */
        [DataMember(Name = "sampleValues", IsRequired = true, EmitDefaultValue = true)]
        public List<string> SampleValues { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MetadataKeyInfoDto {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  IsNumeric: ").Append(IsNumeric).Append("\n");
            sb.Append("  SampleValues: ").Append(SampleValues).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
