/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.34.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// MetadataKeysResponseDto
    /// </summary>
    [DataContract(Name = "MetadataKeysResponseDto")]
    public partial class MetadataKeysResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetadataKeysResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MetadataKeysResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="MetadataKeysResponseDto" /> class.
        /// </summary>
        /// <param name="keys">List of metadata keys with their information (required).</param>
        /// <param name="totalSessions">Total session count in the project (required).</param>
        public MetadataKeysResponseDto(List<MetadataKeyInfoDto> keys = default(List<MetadataKeyInfoDto>), decimal totalSessions = default(decimal))
        {
            // to ensure "keys" is required (not null)
            if (keys == null)
            {
                throw new ArgumentNullException("keys is a required property for MetadataKeysResponseDto and cannot be null");
            }
            this.Keys = keys;
            this.TotalSessions = totalSessions;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// List of metadata keys with their information
        /// </summary>
        /// <value>List of metadata keys with their information</value>
        [DataMember(Name = "keys", IsRequired = true, EmitDefaultValue = true)]
        public List<MetadataKeyInfoDto> Keys { get; set; }

        /// <summary>
        /// Total session count in the project
        /// </summary>
        /// <value>Total session count in the project</value>
        /*
        <example>500</example>
        */
        [DataMember(Name = "totalSessions", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalSessions { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MetadataKeysResponseDto {\n");
            sb.Append("  Keys: ").Append(Keys).Append("\n");
            sb.Append("  TotalSessions: ").Append(TotalSessions).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
