/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.43.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// ModelTransformDto
    /// </summary>
    [DataContract(Name = "ModelTransformDto")]
    public partial class ModelTransformDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelTransformDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ModelTransformDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelTransformDto" /> class.
        /// </summary>
        /// <param name="position">位置 [x, y, z] (required).</param>
        /// <param name="rotation">回転 [x, y, z]（Euler ラジアン） (required).</param>
        /// <param name="scale">スケール [x, y, z]（各成分は 0 より大きい有限数） (required).</param>
        public ModelTransformDto(List<decimal> position = default(List<decimal>), List<decimal> rotation = default(List<decimal>), List<decimal> scale = default(List<decimal>))
        {
            // to ensure "position" is required (not null)
            if (position == null)
            {
                throw new ArgumentNullException("position is a required property for ModelTransformDto and cannot be null");
            }
            this.Position = position;
            // to ensure "rotation" is required (not null)
            if (rotation == null)
            {
                throw new ArgumentNullException("rotation is a required property for ModelTransformDto and cannot be null");
            }
            this.Rotation = rotation;
            // to ensure "scale" is required (not null)
            if (scale == null)
            {
                throw new ArgumentNullException("scale is a required property for ModelTransformDto and cannot be null");
            }
            this.Scale = scale;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// 位置 [x, y, z]
        /// </summary>
        /// <value>位置 [x, y, z]</value>
        /*
        <example>[0,0,0]</example>
        */
        [DataMember(Name = "position", IsRequired = true, EmitDefaultValue = true)]
        public List<decimal> Position { get; set; }

        /// <summary>
        /// 回転 [x, y, z]（Euler ラジアン）
        /// </summary>
        /// <value>回転 [x, y, z]（Euler ラジアン）</value>
        /*
        <example>[0,0,0]</example>
        */
        [DataMember(Name = "rotation", IsRequired = true, EmitDefaultValue = true)]
        public List<decimal> Rotation { get; set; }

        /// <summary>
        /// スケール [x, y, z]（各成分は 0 より大きい有限数）
        /// </summary>
        /// <value>スケール [x, y, z]（各成分は 0 より大きい有限数）</value>
        /*
        <example>[1,1,1]</example>
        */
        [DataMember(Name = "scale", IsRequired = true, EmitDefaultValue = true)]
        public List<decimal> Scale { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ModelTransformDto {\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  Rotation: ").Append(Rotation).Append("\n");
            sb.Append("  Scale: ").Append(Scale).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
