/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.43.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// ModelTransformResponseDto
    /// </summary>
    [DataContract(Name = "ModelTransformResponseDto")]
    public partial class ModelTransformResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelTransformResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ModelTransformResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelTransformResponseDto" /> class.
        /// </summary>
        /// <param name="transform">モデルの配置情報（未設定の場合は null） (required).</param>
        public ModelTransformResponseDto(ModelTransformDto transform = default(ModelTransformDto))
        {
            // to ensure "transform" is required (not null)
            if (transform == null)
            {
                throw new ArgumentNullException("transform is a required property for ModelTransformResponseDto and cannot be null");
            }
            this.Transform = transform;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// モデルの配置情報（未設定の場合は null）
        /// </summary>
        /// <value>モデルの配置情報（未設定の場合は null）</value>
        [DataMember(Name = "transform", IsRequired = true, EmitDefaultValue = true)]
        public ModelTransformDto Transform { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ModelTransformResponseDto {\n");
            sb.Append("  Transform: ").Append(Transform).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
