/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.30.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// NormalizedHeatmapPointDto
    /// </summary>
    [DataContract(Name = "NormalizedHeatmapPointDto")]
    public partial class NormalizedHeatmapPointDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NormalizedHeatmapPointDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NormalizedHeatmapPointDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="NormalizedHeatmapPointDto" /> class.
        /// </summary>
        /// <param name="x">X coordinate (required).</param>
        /// <param name="y">Y coordinate (required).</param>
        /// <param name="z">Z coordinate (required).</param>
        /// <param name="normalizedDensity">Normalized density value (0-1 range) (required).</param>
        public NormalizedHeatmapPointDto(decimal x = default(decimal), decimal y = default(decimal), decimal z = default(decimal), decimal normalizedDensity = default(decimal))
        {
            this.X = x;
            this.Y = y;
            this.Z = z;
            this.NormalizedDensity = normalizedDensity;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// X coordinate
        /// </summary>
        /// <value>X coordinate</value>
        /*
        <example>100.5</example>
        */
        [DataMember(Name = "x", IsRequired = true, EmitDefaultValue = true)]
        public decimal X { get; set; }

        /// <summary>
        /// Y coordinate
        /// </summary>
        /// <value>Y coordinate</value>
        /*
        <example>200.5</example>
        */
        [DataMember(Name = "y", IsRequired = true, EmitDefaultValue = true)]
        public decimal Y { get; set; }

        /// <summary>
        /// Z coordinate
        /// </summary>
        /// <value>Z coordinate</value>
        /*
        <example>50</example>
        */
        [DataMember(Name = "z", IsRequired = true, EmitDefaultValue = true)]
        public decimal Z { get; set; }

        /// <summary>
        /// Normalized density value (0-1 range)
        /// </summary>
        /// <value>Normalized density value (0-1 range)</value>
        /*
        <example>0.75</example>
        */
        [DataMember(Name = "normalizedDensity", IsRequired = true, EmitDefaultValue = true)]
        public decimal NormalizedDensity { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NormalizedHeatmapPointDto {\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Z: ").Append(Z).Append("\n");
            sb.Append("  NormalizedDensity: ").Append(NormalizedDensity).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
