/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.34.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// NormalizedHeatmapStatsDto
    /// </summary>
    [DataContract(Name = "NormalizedHeatmapStatsDto")]
    public partial class NormalizedHeatmapStatsDto
    {
        /// <summary>
        /// Scale mode used for normalization
        /// </summary>
        /// <value>Scale mode used for normalization</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ScaleModeEnum
        {
            /// <summary>
            /// Enum Sqrt for value: sqrt
            /// </summary>
            [EnumMember(Value = "sqrt")]
            Sqrt = 1,

            /// <summary>
            /// Enum Log1p for value: log1p
            /// </summary>
            [EnumMember(Value = "log1p")]
            Log1p = 2
        }


        /// <summary>
        /// Scale mode used for normalization
        /// </summary>
        /// <value>Scale mode used for normalization</value>
        /*
        <example>log1p</example>
        */
        [DataMember(Name = "scaleMode", IsRequired = true, EmitDefaultValue = true)]
        public ScaleModeEnum ScaleMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="NormalizedHeatmapStatsDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NormalizedHeatmapStatsDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="NormalizedHeatmapStatsDto" /> class.
        /// </summary>
        /// <param name="min">Minimum raw density value (required).</param>
        /// <param name="max">Maximum raw density value (required).</param>
        /// <param name="percentile1">1st percentile density value (lower bound for normalization) (required).</param>
        /// <param name="percentile99">99th percentile density value (upper bound for normalization) (required).</param>
        /// <param name="scaleMode">Scale mode used for normalization (required).</param>
        /// <param name="totalPoints">Total number of data points (required).</param>
        public NormalizedHeatmapStatsDto(decimal min = default(decimal), decimal max = default(decimal), decimal percentile1 = default(decimal), decimal percentile99 = default(decimal), ScaleModeEnum scaleMode = default(ScaleModeEnum), decimal totalPoints = default(decimal))
        {
            this.Min = min;
            this.Max = max;
            this.Percentile1 = percentile1;
            this.Percentile99 = percentile99;
            this.ScaleMode = scaleMode;
            this.TotalPoints = totalPoints;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Minimum raw density value
        /// </summary>
        /// <value>Minimum raw density value</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "min", IsRequired = true, EmitDefaultValue = true)]
        public decimal Min { get; set; }

        /// <summary>
        /// Maximum raw density value
        /// </summary>
        /// <value>Maximum raw density value</value>
        /*
        <example>1000</example>
        */
        [DataMember(Name = "max", IsRequired = true, EmitDefaultValue = true)]
        public decimal Max { get; set; }

        /// <summary>
        /// 1st percentile density value (lower bound for normalization)
        /// </summary>
        /// <value>1st percentile density value (lower bound for normalization)</value>
        /*
        <example>5</example>
        */
        [DataMember(Name = "percentile1", IsRequired = true, EmitDefaultValue = true)]
        public decimal Percentile1 { get; set; }

        /// <summary>
        /// 99th percentile density value (upper bound for normalization)
        /// </summary>
        /// <value>99th percentile density value (upper bound for normalization)</value>
        /*
        <example>800</example>
        */
        [DataMember(Name = "percentile99", IsRequired = true, EmitDefaultValue = true)]
        public decimal Percentile99 { get; set; }

        /// <summary>
        /// Total number of data points
        /// </summary>
        /// <value>Total number of data points</value>
        /*
        <example>500</example>
        */
        [DataMember(Name = "totalPoints", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalPoints { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NormalizedHeatmapStatsDto {\n");
            sb.Append("  Min: ").Append(Min).Append("\n");
            sb.Append("  Max: ").Append(Max).Append("\n");
            sb.Append("  Percentile1: ").Append(Percentile1).Append("\n");
            sb.Append("  Percentile99: ").Append(Percentile99).Append("\n");
            sb.Append("  ScaleMode: ").Append(ScaleMode).Append("\n");
            sb.Append("  TotalPoints: ").Append(TotalPoints).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
