/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.43.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// PasswordResetConfirmDto
    /// </summary>
    [DataContract(Name = "PasswordResetConfirmDto")]
    public partial class PasswordResetConfirmDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PasswordResetConfirmDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PasswordResetConfirmDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="PasswordResetConfirmDto" /> class.
        /// </summary>
        /// <param name="token">メールに記載されたリセットトークン (required).</param>
        /// <param name="newPassword">新しいパスワード（8文字以上） (required).</param>
        public PasswordResetConfirmDto(string token = default(string), string newPassword = default(string))
        {
            // to ensure "token" is required (not null)
            if (token == null)
            {
                throw new ArgumentNullException("token is a required property for PasswordResetConfirmDto and cannot be null");
            }
            this.Token = token;
            // to ensure "newPassword" is required (not null)
            if (newPassword == null)
            {
                throw new ArgumentNullException("newPassword is a required property for PasswordResetConfirmDto and cannot be null");
            }
            this.NewPassword = newPassword;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// メールに記載されたリセットトークン
        /// </summary>
        /// <value>メールに記載されたリセットトークン</value>
        [DataMember(Name = "token", IsRequired = true, EmitDefaultValue = true)]
        public string Token { get; set; }

        /// <summary>
        /// 新しいパスワード（8文字以上）
        /// </summary>
        /// <value>新しいパスワード（8文字以上）</value>
        /*
        <example>newPassword123</example>
        */
        [DataMember(Name = "newPassword", IsRequired = true, EmitDefaultValue = true)]
        public string NewPassword { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PasswordResetConfirmDto {\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  NewPassword: ").Append(NewPassword).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
