/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.19.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// PlaySessionResponseDto
    /// </summary>
    [DataContract(Name = "PlaySessionResponseDto")]
    public partial class PlaySessionResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlaySessionResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlaySessionResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlaySessionResponseDto" /> class.
        /// </summary>
        /// <param name="sessionId">sessionId (required).</param>
        /// <param name="projectId">projectId (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="deviceId">deviceId (required).</param>
        /// <param name="platform">platform (required).</param>
        /// <param name="appVersion">appVersion (required).</param>
        /// <param name="metaData">metaData (required).</param>
        /// <param name="startTime">startTime (required).</param>
        /// <param name="endTime">endTime (required).</param>
        /// <param name="isPlaying">isPlaying (required).</param>
        public PlaySessionResponseDto(decimal sessionId = default(decimal), decimal projectId = default(decimal), string name = default(string), string deviceId = default(string), string platform = default(string), string appVersion = default(string), Object metaData = default(Object), DateTime startTime = default(DateTime), DateTime? endTime = default(DateTime?), bool isPlaying = default(bool))
        {
            this.SessionId = sessionId;
            this.ProjectId = projectId;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for PlaySessionResponseDto and cannot be null");
            }
            this.Name = name;
            // to ensure "deviceId" is required (not null)
            if (deviceId == null)
            {
                throw new ArgumentNullException("deviceId is a required property for PlaySessionResponseDto and cannot be null");
            }
            this.DeviceId = deviceId;
            // to ensure "platform" is required (not null)
            if (platform == null)
            {
                throw new ArgumentNullException("platform is a required property for PlaySessionResponseDto and cannot be null");
            }
            this.Platform = platform;
            // to ensure "appVersion" is required (not null)
            if (appVersion == null)
            {
                throw new ArgumentNullException("appVersion is a required property for PlaySessionResponseDto and cannot be null");
            }
            this.AppVersion = appVersion;
            // to ensure "metaData" is required (not null)
            if (metaData == null)
            {
                throw new ArgumentNullException("metaData is a required property for PlaySessionResponseDto and cannot be null");
            }
            this.MetaData = metaData;
            this.StartTime = startTime;
            // to ensure "endTime" is required (not null)
            if (endTime == null)
            {
                throw new ArgumentNullException("endTime is a required property for PlaySessionResponseDto and cannot be null");
            }
            this.EndTime = endTime;
            this.IsPlaying = isPlaying;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets SessionId
        /// </summary>
        [DataMember(Name = "sessionId", IsRequired = true, EmitDefaultValue = true)]
        public decimal SessionId { get; set; }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [DataMember(Name = "projectId", IsRequired = true, EmitDefaultValue = true)]
        public decimal ProjectId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets DeviceId
        /// </summary>
        [DataMember(Name = "deviceId", IsRequired = true, EmitDefaultValue = true)]
        public string DeviceId { get; set; }

        /// <summary>
        /// Gets or Sets Platform
        /// </summary>
        /*
        <example>platform</example>
        */
        [DataMember(Name = "platform", IsRequired = true, EmitDefaultValue = true)]
        public string Platform { get; set; }

        /// <summary>
        /// Gets or Sets AppVersion
        /// </summary>
        /*
        <example>app_version</example>
        */
        [DataMember(Name = "appVersion", IsRequired = true, EmitDefaultValue = true)]
        public string AppVersion { get; set; }

        /// <summary>
        /// Gets or Sets MetaData
        /// </summary>
        /*
        <example>meta_data</example>
        */
        [DataMember(Name = "metaData", IsRequired = true, EmitDefaultValue = true)]
        public Object MetaData { get; set; }

        /// <summary>
        /// Gets or Sets StartTime
        /// </summary>
        [DataMember(Name = "startTime", IsRequired = true, EmitDefaultValue = true)]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// Gets or Sets EndTime
        /// </summary>
        [DataMember(Name = "endTime", IsRequired = true, EmitDefaultValue = true)]
        public DateTime? EndTime { get; set; }

        /// <summary>
        /// Gets or Sets IsPlaying
        /// </summary>
        /*
        <example>false</example>
        */
        [DataMember(Name = "isPlaying", IsRequired = true, EmitDefaultValue = true)]
        public bool IsPlaying { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlaySessionResponseDto {\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DeviceId: ").Append(DeviceId).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  AppVersion: ").Append(AppVersion).Append("\n");
            sb.Append("  MetaData: ").Append(MetaData).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  IsPlaying: ").Append(IsPlaying).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
