/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.16.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// PlayPositionLogDto
    /// </summary>
    [DataContract(Name = "PlayPositionLogDto")]
    public partial class PlayPositionLogDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayPositionLogDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlayPositionLogDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayPositionLogDto" /> class.
        /// </summary>
        /// <param name="player">Player identifier (required).</param>
        /// <param name="x">X coordinate (required).</param>
        /// <param name="y">Y coordinate (required).</param>
        /// <param name="z">Z coordinate.</param>
        /// <param name="offsetTimestamp">Milliseconds since session start (required).</param>
        /// <param name="location">Location name or identifier.</param>
        /// <param name="status">Player status data (health, state, score, etc.).</param>
        public PlayPositionLogDto(decimal player = default(decimal), decimal x = default(decimal), decimal y = default(decimal), decimal? z = default(decimal?), int offsetTimestamp = default(int), string location = default(string), Object status = default(Object))
        {
            this.Player = player;
            this.X = x;
            this.Y = y;
            this.OffsetTimestamp = offsetTimestamp;
            this.Z = z;
            this.Location = location;
            this.Status = status;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Player identifier
        /// </summary>
        /// <value>Player identifier</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "player", IsRequired = true, EmitDefaultValue = true)]
        public decimal Player { get; set; }

        /// <summary>
        /// X coordinate
        /// </summary>
        /// <value>X coordinate</value>
        [DataMember(Name = "x", IsRequired = true, EmitDefaultValue = true)]
        public decimal X { get; set; }

        /// <summary>
        /// Y coordinate
        /// </summary>
        /// <value>Y coordinate</value>
        [DataMember(Name = "y", IsRequired = true, EmitDefaultValue = true)]
        public decimal Y { get; set; }

        /// <summary>
        /// Z coordinate
        /// </summary>
        /// <value>Z coordinate</value>
        [DataMember(Name = "z", EmitDefaultValue = true)]
        public decimal? Z { get; set; }

        /// <summary>
        /// Milliseconds since session start
        /// </summary>
        /// <value>Milliseconds since session start</value>
        [DataMember(Name = "offset_timestamp", IsRequired = true, EmitDefaultValue = true)]
        public int OffsetTimestamp { get; set; }

        /// <summary>
        /// Location name or identifier
        /// </summary>
        /// <value>Location name or identifier</value>
        [DataMember(Name = "location", EmitDefaultValue = true)]
        public string Location { get; set; }

        /// <summary>
        /// Player status data (health, state, score, etc.)
        /// </summary>
        /// <value>Player status data (health, state, score, etc.)</value>
        /*
        <example>{&quot;health&quot;:100,&quot;state&quot;:&quot;running&quot;,&quot;score&quot;:1000}</example>
        */
        [DataMember(Name = "status", EmitDefaultValue = true)]
        public Object Status { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayPositionLogDto {\n");
            sb.Append("  Player: ").Append(Player).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Z: ").Append(Z).Append("\n");
            sb.Append("  OffsetTimestamp: ").Append(OffsetTimestamp).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
