/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.19.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// PublicStatsResponseDto
    /// </summary>
    [DataContract(Name = "PublicStatsResponseDto")]
    public partial class PublicStatsResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicStatsResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PublicStatsResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicStatsResponseDto" /> class.
        /// </summary>
        /// <param name="totalProjects">総プロジェクト数 (required).</param>
        /// <param name="totalSessions">総セッション数 (required).</param>
        /// <param name="totalEvents">総イベント数（処理済み） (required).</param>
        /// <param name="activeSessions7d">過去7日間のアクティブセッション数 (required).</param>
        /// <param name="totalUsers">総ユーザー数 (required).</param>
        public PublicStatsResponseDto(decimal totalProjects = default(decimal), decimal totalSessions = default(decimal), decimal totalEvents = default(decimal), decimal activeSessions7d = default(decimal), decimal totalUsers = default(decimal))
        {
            this.TotalProjects = totalProjects;
            this.TotalSessions = totalSessions;
            this.TotalEvents = totalEvents;
            this.ActiveSessions7d = activeSessions7d;
            this.TotalUsers = totalUsers;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// 総プロジェクト数
        /// </summary>
        /// <value>総プロジェクト数</value>
        /*
        <example>150</example>
        */
        [DataMember(Name = "total_projects", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalProjects { get; set; }

        /// <summary>
        /// 総セッション数
        /// </summary>
        /// <value>総セッション数</value>
        /*
        <example>1234</example>
        */
        [DataMember(Name = "total_sessions", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalSessions { get; set; }

        /// <summary>
        /// 総イベント数（処理済み）
        /// </summary>
        /// <value>総イベント数（処理済み）</value>
        /*
        <example>567890</example>
        */
        [DataMember(Name = "total_events", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalEvents { get; set; }

        /// <summary>
        /// 過去7日間のアクティブセッション数
        /// </summary>
        /// <value>過去7日間のアクティブセッション数</value>
        /*
        <example>42</example>
        */
        [DataMember(Name = "active_sessions_7d", IsRequired = true, EmitDefaultValue = true)]
        public decimal ActiveSessions7d { get; set; }

        /// <summary>
        /// 総ユーザー数
        /// </summary>
        /// <value>総ユーザー数</value>
        /*
        <example>89</example>
        */
        [DataMember(Name = "total_users", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalUsers { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PublicStatsResponseDto {\n");
            sb.Append("  TotalProjects: ").Append(TotalProjects).Append("\n");
            sb.Append("  TotalSessions: ").Append(TotalSessions).Append("\n");
            sb.Append("  TotalEvents: ").Append(TotalEvents).Append("\n");
            sb.Append("  ActiveSessions7d: ").Append(ActiveSessions7d).Append("\n");
            sb.Append("  TotalUsers: ").Append(TotalUsers).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
