/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.19.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// RawRouteDto
    /// </summary>
    [DataContract(Name = "RawRouteDto")]
    public partial class RawRouteDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RawRouteDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RawRouteDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="RawRouteDto" /> class.
        /// </summary>
        /// <param name="id">Route ID (required).</param>
        /// <param name="playerId">Player ID (required).</param>
        /// <param name="sessionId">Session ID (required).</param>
        /// <param name="trajectoryPoints">Trajectory points leading to the cluster (raw player position logs) (required).</param>
        /// <param name="durationMs">Duration in milliseconds.</param>
        public RawRouteDto(decimal id = default(decimal), string playerId = default(string), decimal sessionId = default(decimal), List<RawRouteDtoTrajectoryPointsInner> trajectoryPoints = default(List<RawRouteDtoTrajectoryPointsInner>), decimal durationMs = default(decimal))
        {
            this.Id = id;
            // to ensure "playerId" is required (not null)
            if (playerId == null)
            {
                throw new ArgumentNullException("playerId is a required property for RawRouteDto and cannot be null");
            }
            this.PlayerId = playerId;
            this.SessionId = sessionId;
            // to ensure "trajectoryPoints" is required (not null)
            if (trajectoryPoints == null)
            {
                throw new ArgumentNullException("trajectoryPoints is a required property for RawRouteDto and cannot be null");
            }
            this.TrajectoryPoints = trajectoryPoints;
            this.DurationMs = durationMs;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Route ID
        /// </summary>
        /// <value>Route ID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public decimal Id { get; set; }

        /// <summary>
        /// Player ID
        /// </summary>
        /// <value>Player ID</value>
        [DataMember(Name = "player_id", IsRequired = true, EmitDefaultValue = true)]
        public string PlayerId { get; set; }

        /// <summary>
        /// Session ID
        /// </summary>
        /// <value>Session ID</value>
        [DataMember(Name = "session_id", IsRequired = true, EmitDefaultValue = true)]
        public decimal SessionId { get; set; }

        /// <summary>
        /// Trajectory points leading to the cluster (raw player position logs)
        /// </summary>
        /// <value>Trajectory points leading to the cluster (raw player position logs)</value>
        [DataMember(Name = "trajectory_points", IsRequired = true, EmitDefaultValue = true)]
        public List<RawRouteDtoTrajectoryPointsInner> TrajectoryPoints { get; set; }

        /// <summary>
        /// Duration in milliseconds
        /// </summary>
        /// <value>Duration in milliseconds</value>
        [DataMember(Name = "duration_ms", EmitDefaultValue = false)]
        public decimal DurationMs { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RawRouteDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PlayerId: ").Append(PlayerId).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  TrajectoryPoints: ").Append(TrajectoryPoints).Append("\n");
            sb.Append("  DurationMs: ").Append(DurationMs).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
