/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.31.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// ScreenshotStorageStatusDto
    /// </summary>
    [DataContract(Name = "ScreenshotStorageStatusDto")]
    public partial class ScreenshotStorageStatusDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScreenshotStorageStatusDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScreenshotStorageStatusDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScreenshotStorageStatusDto" /> class.
        /// </summary>
        /// <param name="enabled">Whether screenshot storage is enabled (required).</param>
        public ScreenshotStorageStatusDto(bool enabled = default(bool))
        {
            this.Enabled = enabled;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Whether screenshot storage is enabled
        /// </summary>
        /// <value>Whether screenshot storage is enabled</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ScreenshotStorageStatusDto {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
