/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.31.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// SearchSessionSummaryResponseDto
    /// </summary>
    [DataContract(Name = "SearchSessionSummaryResponseDto")]
    public partial class SearchSessionSummaryResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchSessionSummaryResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchSessionSummaryResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchSessionSummaryResponseDto" /> class.
        /// </summary>
        /// <param name="sessions">Array of session summaries matching the search criteria (no pagination) (required).</param>
        /// <param name="total">Total number of sessions found (required).</param>
        public SearchSessionSummaryResponseDto(List<SearchSessionSummaryDto> sessions = default(List<SearchSessionSummaryDto>), decimal total = default(decimal))
        {
            // to ensure "sessions" is required (not null)
            if (sessions == null)
            {
                throw new ArgumentNullException("sessions is a required property for SearchSessionSummaryResponseDto and cannot be null");
            }
            this.Sessions = sessions;
            this.Total = total;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Array of session summaries matching the search criteria (no pagination)
        /// </summary>
        /// <value>Array of session summaries matching the search criteria (no pagination)</value>
        [DataMember(Name = "sessions", IsRequired = true, EmitDefaultValue = true)]
        public List<SearchSessionSummaryDto> Sessions { get; set; }

        /// <summary>
        /// Total number of sessions found
        /// </summary>
        /// <value>Total number of sessions found</value>
        /*
        <example>42</example>
        */
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public decimal Total { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchSessionSummaryResponseDto {\n");
            sb.Append("  Sessions: ").Append(Sessions).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
