/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// SearchPlaySessionResponseDto
    /// </summary>
    [DataContract(Name = "SearchPlaySessionResponseDto")]
    public partial class SearchPlaySessionResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchPlaySessionResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchPlaySessionResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchPlaySessionResponseDto" /> class.
        /// </summary>
        /// <param name="data">Array of play sessions matching the search criteria (required).</param>
        /// <param name="total">Total number of sessions matching the criteria (required).</param>
        /// <param name="limit">Number of results returned (required).</param>
        /// <param name="offset">Number of results skipped (required).</param>
        public SearchPlaySessionResponseDto(List<PlaySessionResponseDto> data = default(List<PlaySessionResponseDto>), decimal total = default(decimal), decimal limit = default(decimal), decimal offset = default(decimal))
        {
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for SearchPlaySessionResponseDto and cannot be null");
            }
            this.Data = data;
            this.Total = total;
            this.Limit = limit;
            this.Offset = offset;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Array of play sessions matching the search criteria
        /// </summary>
        /// <value>Array of play sessions matching the search criteria</value>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public List<PlaySessionResponseDto> Data { get; set; }

        /// <summary>
        /// Total number of sessions matching the criteria
        /// </summary>
        /// <value>Total number of sessions matching the criteria</value>
        /*
        <example>100</example>
        */
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public decimal Total { get; set; }

        /// <summary>
        /// Number of results returned
        /// </summary>
        /// <value>Number of results returned</value>
        /*
        <example>20</example>
        */
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public decimal Limit { get; set; }

        /// <summary>
        /// Number of results skipped
        /// </summary>
        /// <value>Number of results skipped</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "offset", IsRequired = true, EmitDefaultValue = true)]
        public decimal Offset { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchPlaySessionResponseDto {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
