/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.19.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// SearchSessionSummaryDto
    /// </summary>
    [DataContract(Name = "SearchSessionSummaryDto")]
    public partial class SearchSessionSummaryDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchSessionSummaryDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchSessionSummaryDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchSessionSummaryDto" /> class.
        /// </summary>
        /// <param name="id">Session ID (required).</param>
        /// <param name="display">Display text for the session (includes name, platform, version, and start time) (required).</param>
        public SearchSessionSummaryDto(decimal id = default(decimal), string display = default(string))
        {
            this.Id = id;
            // to ensure "display" is required (not null)
            if (display == null)
            {
                throw new ArgumentNullException("display is a required property for SearchSessionSummaryDto and cannot be null");
            }
            this.Display = display;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Session ID
        /// </summary>
        /// <value>Session ID</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public decimal Id { get; set; }

        /// <summary>
        /// Display text for the session (includes name, platform, version, and start time)
        /// </summary>
        /// <value>Display text for the session (includes name, platform, version, and start time)</value>
        /*
        <example>Session_2025-01-15_Morning (Android, v1.2.3) - 2025-01-15 10:30</example>
        */
        [DataMember(Name = "display", IsRequired = true, EmitDefaultValue = true)]
        public string Display { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchSessionSummaryDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Display: ").Append(Display).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
