/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.17.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// SessionSummaryDto
    /// </summary>
    [DataContract(Name = "SessionSummaryDto")]
    public partial class SessionSummaryDto
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Queued for value: queued
            /// </summary>
            [EnumMember(Value = "queued")]
            Queued = 1,

            /// <summary>
            /// Enum Running for value: running
            /// </summary>
            [EnumMember(Value = "running")]
            Running = 2,

            /// <summary>
            /// Enum Done for value: done
            /// </summary>
            [EnumMember(Value = "done")]
            Done = 3,

            /// <summary>
            /// Enum Error for value: error
            /// </summary>
            [EnumMember(Value = "error")]
            Error = 4
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Summary language
        /// </summary>
        /// <value>Summary language</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LangEnum
        {
            /// <summary>
            /// Enum Ja for value: ja
            /// </summary>
            [EnumMember(Value = "ja")]
            Ja = 1,

            /// <summary>
            /// Enum En for value: en
            /// </summary>
            [EnumMember(Value = "en")]
            En = 2
        }


        /// <summary>
        /// Summary language
        /// </summary>
        /// <value>Summary language</value>
        [DataMember(Name = "lang", IsRequired = true, EmitDefaultValue = true)]
        public LangEnum Lang { get; set; }
        /// <summary>
        /// AI provider used for generation
        /// </summary>
        /// <value>AI provider used for generation</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProviderEnum
        {
            /// <summary>
            /// Enum Template for value: template
            /// </summary>
            [EnumMember(Value = "template")]
            Template = 1,

            /// <summary>
            /// Enum Ollama for value: ollama
            /// </summary>
            [EnumMember(Value = "ollama")]
            Ollama = 2,

            /// <summary>
            /// Enum Openai for value: openai
            /// </summary>
            [EnumMember(Value = "openai")]
            Openai = 3
        }


        /// <summary>
        /// AI provider used for generation
        /// </summary>
        /// <value>AI provider used for generation</value>
        [DataMember(Name = "provider", IsRequired = true, EmitDefaultValue = true)]
        public ProviderEnum Provider { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SessionSummaryDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SessionSummaryDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SessionSummaryDto" /> class.
        /// </summary>
        /// <param name="id">Summary UUID (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="lang">Summary language (required).</param>
        /// <param name="provider">AI provider used for generation (required).</param>
        /// <param name="model">AI model name (required).</param>
        /// <param name="summaryMd">Summary in Markdown format (required).</param>
        /// <param name="summaryJson">Summary in JSON format with structured data (required).</param>
        /// <param name="createdAt">Summary creation timestamp (required).</param>
        public SessionSummaryDto(string id = default(string), StatusEnum status = default(StatusEnum), LangEnum lang = default(LangEnum), ProviderEnum provider = default(ProviderEnum), string model = default(string), string summaryMd = default(string), Dictionary<string, Object> summaryJson = default(Dictionary<string, Object>), DateTime createdAt = default(DateTime))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for SessionSummaryDto and cannot be null");
            }
            this.Id = id;
            this.Status = status;
            this.Lang = lang;
            this.Provider = provider;
            // to ensure "model" is required (not null)
            if (model == null)
            {
                throw new ArgumentNullException("model is a required property for SessionSummaryDto and cannot be null");
            }
            this.Model = model;
            // to ensure "summaryMd" is required (not null)
            if (summaryMd == null)
            {
                throw new ArgumentNullException("summaryMd is a required property for SessionSummaryDto and cannot be null");
            }
            this.SummaryMd = summaryMd;
            // to ensure "summaryJson" is required (not null)
            if (summaryJson == null)
            {
                throw new ArgumentNullException("summaryJson is a required property for SessionSummaryDto and cannot be null");
            }
            this.SummaryJson = summaryJson;
            this.CreatedAt = createdAt;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Summary UUID
        /// </summary>
        /// <value>Summary UUID</value>
        /*
        <example>8c7b3c7a-1c6a-41a4-9a9b-9b1c1d2e3f4a</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// AI model name
        /// </summary>
        /// <value>AI model name</value>
        /*
        <example>gpt-4o-mini</example>
        */
        [DataMember(Name = "model", IsRequired = true, EmitDefaultValue = true)]
        public string Model { get; set; }

        /// <summary>
        /// Summary in Markdown format
        /// </summary>
        /// <value>Summary in Markdown format</value>
        [DataMember(Name = "summary_md", IsRequired = true, EmitDefaultValue = true)]
        public string SummaryMd { get; set; }

        /// <summary>
        /// Summary in JSON format with structured data
        /// </summary>
        /// <value>Summary in JSON format with structured data</value>
        /*
        <example>{&quot;title&quot;:&quot;Session Summary&quot;,&quot;description&quot;:&quot;Player completed level 1&quot;,&quot;keyFindings&quot;:[&quot;Fast completion&quot;,&quot;No deaths&quot;]}</example>
        */
        [DataMember(Name = "summary_json", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> SummaryJson { get; set; }

        /// <summary>
        /// Summary creation timestamp
        /// </summary>
        /// <value>Summary creation timestamp</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SessionSummaryDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Lang: ").Append(Lang).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  SummaryMd: ").Append(SummaryMd).Append("\n");
            sb.Append("  SummaryJson: ").Append(SummaryJson).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
