/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.43.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// SignupCompleteDto
    /// </summary>
    [DataContract(Name = "SignupCompleteDto")]
    public partial class SignupCompleteDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignupCompleteDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SignupCompleteDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignupCompleteDto" /> class.
        /// </summary>
        /// <param name="email">認証コードを送ったメールアドレス (required).</param>
        /// <param name="code">メールに記載された6桁の認証コード (required).</param>
        /// <param name="password">設定するパスワード（8文字以上） (required).</param>
        public SignupCompleteDto(string email = default(string), string code = default(string), string password = default(string))
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for SignupCompleteDto and cannot be null");
            }
            this.Email = email;
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for SignupCompleteDto and cannot be null");
            }
            this.Code = code;
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for SignupCompleteDto and cannot be null");
            }
            this.Password = password;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// 認証コードを送ったメールアドレス
        /// </summary>
        /// <value>認証コードを送ったメールアドレス</value>
        /*
        <example>user@example.com</example>
        */
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// メールに記載された6桁の認証コード
        /// </summary>
        /// <value>メールに記載された6桁の認証コード</value>
        /*
        <example>123456</example>
        */
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// 設定するパスワード（8文字以上）
        /// </summary>
        /// <value>設定するパスワード（8文字以上）</value>
        /*
        <example>myPassword123</example>
        */
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignupCompleteDto {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
