/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// StringGeneralLogDto
    /// </summary>
    [DataContract(Name = "StringGeneralLogDto")]
    public partial class StringGeneralLogDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StringGeneralLogDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StringGeneralLogDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="StringGeneralLogDto" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="eventType">eventType (required).</param>
        /// <param name="eventData">eventData (required).</param>
        /// <param name="offsetTimestamp">offsetTimestamp (required).</param>
        /// <param name="player">player (required).</param>
        public StringGeneralLogDto(decimal id = default(decimal), string eventType = default(string), StringGeneralLogDataDto eventData = default(StringGeneralLogDataDto), decimal offsetTimestamp = default(decimal), int player = default(int))
        {
            this.Id = id;
            // to ensure "eventType" is required (not null)
            if (eventType == null)
            {
                throw new ArgumentNullException("eventType is a required property for StringGeneralLogDto and cannot be null");
            }
            this.EventType = eventType;
            // to ensure "eventData" is required (not null)
            if (eventData == null)
            {
                throw new ArgumentNullException("eventData is a required property for StringGeneralLogDto and cannot be null");
            }
            this.EventData = eventData;
            this.OffsetTimestamp = offsetTimestamp;
            this.Player = player;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public decimal Id { get; set; }

        /// <summary>
        /// Gets or Sets EventType
        /// </summary>
        [DataMember(Name = "event_type", IsRequired = true, EmitDefaultValue = true)]
        public string EventType { get; set; }

        /// <summary>
        /// Gets or Sets EventData
        /// </summary>
        [DataMember(Name = "event_data", IsRequired = true, EmitDefaultValue = true)]
        public StringGeneralLogDataDto EventData { get; set; }

        /// <summary>
        /// Gets or Sets OffsetTimestamp
        /// </summary>
        [DataMember(Name = "offset_timestamp", IsRequired = true, EmitDefaultValue = true)]
        public decimal OffsetTimestamp { get; set; }

        /// <summary>
        /// Gets or Sets Player
        /// </summary>
        [DataMember(Name = "player", IsRequired = true, EmitDefaultValue = true)]
        public int Player { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StringGeneralLogDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  EventData: ").Append(EventData).Append("\n");
            sb.Append("  OffsetTimestamp: ").Append(OffsetTimestamp).Append("\n");
            sb.Append("  Player: ").Append(Player).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
