/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.19.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// SubmitImprovementRouteFeedbackResponseDto
    /// </summary>
    [DataContract(Name = "SubmitImprovementRouteFeedbackResponseDto")]
    public partial class SubmitImprovementRouteFeedbackResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitImprovementRouteFeedbackResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SubmitImprovementRouteFeedbackResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitImprovementRouteFeedbackResponseDto" /> class.
        /// </summary>
        /// <param name="improvementRouteId">Improvement route ID (required).</param>
        /// <param name="feedbackTotalCount">Total feedback count for this improvement route (required).</param>
        /// <param name="feedbackAvgRating">Average feedback rating (1-3) (required).</param>
        /// <param name="feedbacks">All feedback records for this improvement route (required).</param>
        public SubmitImprovementRouteFeedbackResponseDto(decimal improvementRouteId = default(decimal), decimal feedbackTotalCount = default(decimal), decimal feedbackAvgRating = default(decimal), List<ImprovementRouteFeedbackRecordDto> feedbacks = default(List<ImprovementRouteFeedbackRecordDto>))
        {
            this.ImprovementRouteId = improvementRouteId;
            this.FeedbackTotalCount = feedbackTotalCount;
            this.FeedbackAvgRating = feedbackAvgRating;
            // to ensure "feedbacks" is required (not null)
            if (feedbacks == null)
            {
                throw new ArgumentNullException("feedbacks is a required property for SubmitImprovementRouteFeedbackResponseDto and cannot be null");
            }
            this.Feedbacks = feedbacks;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Improvement route ID
        /// </summary>
        /// <value>Improvement route ID</value>
        [DataMember(Name = "improvement_route_id", IsRequired = true, EmitDefaultValue = true)]
        public decimal ImprovementRouteId { get; set; }

        /// <summary>
        /// Total feedback count for this improvement route
        /// </summary>
        /// <value>Total feedback count for this improvement route</value>
        [DataMember(Name = "feedback_total_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal FeedbackTotalCount { get; set; }

        /// <summary>
        /// Average feedback rating (1-3)
        /// </summary>
        /// <value>Average feedback rating (1-3)</value>
        [DataMember(Name = "feedback_avg_rating", IsRequired = true, EmitDefaultValue = true)]
        public decimal FeedbackAvgRating { get; set; }

        /// <summary>
        /// All feedback records for this improvement route
        /// </summary>
        /// <value>All feedback records for this improvement route</value>
        [DataMember(Name = "feedbacks", IsRequired = true, EmitDefaultValue = true)]
        public List<ImprovementRouteFeedbackRecordDto> Feedbacks { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubmitImprovementRouteFeedbackResponseDto {\n");
            sb.Append("  ImprovementRouteId: ").Append(ImprovementRouteId).Append("\n");
            sb.Append("  FeedbackTotalCount: ").Append(FeedbackTotalCount).Append("\n");
            sb.Append("  FeedbackAvgRating: ").Append(FeedbackAvgRating).Append("\n");
            sb.Append("  Feedbacks: ").Append(Feedbacks).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
