/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.19.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// SubmitImprovementRouteFeedbackRequestDto
    /// </summary>
    [DataContract(Name = "SubmitImprovementRouteFeedbackRequestDto")]
    public partial class SubmitImprovementRouteFeedbackRequestDto
    {
        /// <summary>
        /// Rating: 1&#x3D;Bad (👎), 2&#x3D;Neutral (😐), 3&#x3D;Good (👍)
        /// </summary>
        /// <value>Rating: 1&#x3D;Bad (👎), 2&#x3D;Neutral (😐), 3&#x3D;Good (👍)</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RatingEnum
        {
            /// <summary>
            /// Enum _1 for value: 1
            /// </summary>
            [EnumMember(Value = "1")]
            _1 = 1,

            /// <summary>
            /// Enum _2 for value: 2
            /// </summary>
            [EnumMember(Value = "2")]
            _2 = 2,

            /// <summary>
            /// Enum _3 for value: 3
            /// </summary>
            [EnumMember(Value = "3")]
            _3 = 3
        }


        /// <summary>
        /// Rating: 1&#x3D;Bad (👎), 2&#x3D;Neutral (😐), 3&#x3D;Good (👍)
        /// </summary>
        /// <value>Rating: 1&#x3D;Bad (👎), 2&#x3D;Neutral (😐), 3&#x3D;Good (👍)</value>
        [DataMember(Name = "rating", IsRequired = true, EmitDefaultValue = true)]
        public RatingEnum Rating { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitImprovementRouteFeedbackRequestDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SubmitImprovementRouteFeedbackRequestDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitImprovementRouteFeedbackRequestDto" /> class.
        /// </summary>
        /// <param name="rating">Rating: 1&#x3D;Bad (👎), 2&#x3D;Neutral (😐), 3&#x3D;Good (👍) (required).</param>
        /// <param name="comment">Optional comment about the improvement.</param>
        public SubmitImprovementRouteFeedbackRequestDto(RatingEnum rating = default(RatingEnum), string comment = default(string))
        {
            this.Rating = rating;
            this.Comment = comment;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Optional comment about the improvement
        /// </summary>
        /// <value>Optional comment about the improvement</value>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubmitImprovementRouteFeedbackRequestDto {\n");
            sb.Append("  Rating: ").Append(Rating).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
