/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.19.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// UpdateRoleDto
    /// </summary>
    [DataContract(Name = "UpdateRoleDto")]
    public partial class UpdateRoleDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRoleDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateRoleDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRoleDto" /> class.
        /// </summary>
        /// <param name="role">ユーザーの新しいロール (例: user, admin) (required).</param>
        public UpdateRoleDto(string role = default(string))
        {
            // to ensure "role" is required (not null)
            if (role == null)
            {
                throw new ArgumentNullException("role is a required property for UpdateRoleDto and cannot be null");
            }
            this.Role = role;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// ユーザーの新しいロール (例: user, admin)
        /// </summary>
        /// <value>ユーザーの新しいロール (例: user, admin)</value>
        /*
        <example>admin</example>
        */
        [DataMember(Name = "role", IsRequired = true, EmitDefaultValue = true)]
        public string Role { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateRoleDto {\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
