/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.31.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// UpdateGameApiKeyProjectsDto
    /// </summary>
    [DataContract(Name = "UpdateGameApiKeyProjectsDto")]
    public partial class UpdateGameApiKeyProjectsDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateGameApiKeyProjectsDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateGameApiKeyProjectsDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateGameApiKeyProjectsDto" /> class.
        /// </summary>
        /// <param name="projectIds">アクセスを許可するプロジェクトIDのリスト (required).</param>
        public UpdateGameApiKeyProjectsDto(List<decimal> projectIds = default(List<decimal>))
        {
            // to ensure "projectIds" is required (not null)
            if (projectIds == null)
            {
                throw new ArgumentNullException("projectIds is a required property for UpdateGameApiKeyProjectsDto and cannot be null");
            }
            this.ProjectIds = projectIds;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// アクセスを許可するプロジェクトIDのリスト
        /// </summary>
        /// <value>アクセスを許可するプロジェクトIDのリスト</value>
        /*
        <example>[1,2,3]</example>
        */
        [DataMember(Name = "projectIds", IsRequired = true, EmitDefaultValue = true)]
        public List<decimal> ProjectIds { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateGameApiKeyProjectsDto {\n");
            sb.Append("  ProjectIds: ").Append(ProjectIds).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
