/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.34.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// UpdateUserPasswordDto
    /// </summary>
    [DataContract(Name = "UpdateUserPasswordDto")]
    public partial class UpdateUserPasswordDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateUserPasswordDto" /> class.
        /// </summary>
        /// <param name="password">新しいパスワード（6文字以上）.</param>
        /// <param name="clearPassword">trueの場合、パスワードをクリア（OAuth専用ユーザーにする）.</param>
        public UpdateUserPasswordDto(string password = default(string), bool clearPassword = default(bool))
        {
            this.Password = password;
            this.ClearPassword = clearPassword;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// 新しいパスワード（6文字以上）
        /// </summary>
        /// <value>新しいパスワード（6文字以上）</value>
        /*
        <example>newPassword123</example>
        */
        [DataMember(Name = "password", EmitDefaultValue = false)]
        public string Password { get; set; }

        /// <summary>
        /// trueの場合、パスワードをクリア（OAuth専用ユーザーにする）
        /// </summary>
        /// <value>trueの場合、パスワードをクリア（OAuth専用ユーザーにする）</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "clearPassword", EmitDefaultValue = true)]
        public bool ClearPassword { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateUserPasswordDto {\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  ClearPassword: ").Append(ClearPassword).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
