/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.38.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// UpdatePasswordDto
    /// </summary>
    [DataContract(Name = "UpdatePasswordDto")]
    public partial class UpdatePasswordDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePasswordDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdatePasswordDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePasswordDto" /> class.
        /// </summary>
        /// <param name="currentPassword">現在のパスワード (required).</param>
        /// <param name="newPassword">新しいパスワード（8文字以上） (required).</param>
        public UpdatePasswordDto(string currentPassword = default(string), string newPassword = default(string))
        {
            // to ensure "currentPassword" is required (not null)
            if (currentPassword == null)
            {
                throw new ArgumentNullException("currentPassword is a required property for UpdatePasswordDto and cannot be null");
            }
            this.CurrentPassword = currentPassword;
            // to ensure "newPassword" is required (not null)
            if (newPassword == null)
            {
                throw new ArgumentNullException("newPassword is a required property for UpdatePasswordDto and cannot be null");
            }
            this.NewPassword = newPassword;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// 現在のパスワード
        /// </summary>
        /// <value>現在のパスワード</value>
        /*
        <example>currentPassword123</example>
        */
        [DataMember(Name = "currentPassword", IsRequired = true, EmitDefaultValue = true)]
        public string CurrentPassword { get; set; }

        /// <summary>
        /// 新しいパスワード（8文字以上）
        /// </summary>
        /// <value>新しいパスワード（8文字以上）</value>
        /*
        <example>newPassword123</example>
        */
        [DataMember(Name = "newPassword", IsRequired = true, EmitDefaultValue = true)]
        public string NewPassword { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdatePasswordDto {\n");
            sb.Append("  CurrentPassword: ").Append(CurrentPassword).Append("\n");
            sb.Append("  NewPassword: ").Append(NewPassword).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
