/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.38.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// UpdatePasswordV01Dto
    /// </summary>
    [DataContract(Name = "UpdatePasswordV01Dto")]
    public partial class UpdatePasswordV01Dto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePasswordV01Dto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdatePasswordV01Dto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePasswordV01Dto" /> class.
        /// </summary>
        /// <param name="currentPassword">現在のパスワード。OAuth等でまだパスワード未設定のユーザーは省略可.</param>
        /// <param name="newPassword">新しいパスワード（8文字以上） (required).</param>
        public UpdatePasswordV01Dto(string currentPassword = default(string), string newPassword = default(string))
        {
            // to ensure "newPassword" is required (not null)
            if (newPassword == null)
            {
                throw new ArgumentNullException("newPassword is a required property for UpdatePasswordV01Dto and cannot be null");
            }
            this.NewPassword = newPassword;
            this.CurrentPassword = currentPassword;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// 現在のパスワード。OAuth等でまだパスワード未設定のユーザーは省略可
        /// </summary>
        /// <value>現在のパスワード。OAuth等でまだパスワード未設定のユーザーは省略可</value>
        /*
        <example>currentPassword123</example>
        */
        [DataMember(Name = "currentPassword", EmitDefaultValue = false)]
        public string CurrentPassword { get; set; }

        /// <summary>
        /// 新しいパスワード（8文字以上）
        /// </summary>
        /// <value>新しいパスワード（8文字以上）</value>
        /*
        <example>newPassword123</example>
        */
        [DataMember(Name = "newPassword", IsRequired = true, EmitDefaultValue = true)]
        public string NewPassword { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdatePasswordV01Dto {\n");
            sb.Append("  CurrentPassword: ").Append(CurrentPassword).Append("\n");
            sb.Append("  NewPassword: ").Append(NewPassword).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
