/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.31.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// VerifyEmbedTokenResponseDto
    /// </summary>
    [DataContract(Name = "VerifyEmbedTokenResponseDto")]
    public partial class VerifyEmbedTokenResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyEmbedTokenResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VerifyEmbedTokenResponseDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyEmbedTokenResponseDto" /> class.
        /// </summary>
        /// <param name="projectId">プロジェクトID (required).</param>
        /// <param name="sessionId">セッションID (required).</param>
        /// <param name="expiresAt">トークンの有効期限（ISO 8601形式） (required).</param>
        public VerifyEmbedTokenResponseDto(decimal projectId = default(decimal), decimal sessionId = default(decimal), string expiresAt = default(string))
        {
            this.ProjectId = projectId;
            this.SessionId = sessionId;
            // to ensure "expiresAt" is required (not null)
            if (expiresAt == null)
            {
                throw new ArgumentNullException("expiresAt is a required property for VerifyEmbedTokenResponseDto and cannot be null");
            }
            this.ExpiresAt = expiresAt;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// プロジェクトID
        /// </summary>
        /// <value>プロジェクトID</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "projectId", IsRequired = true, EmitDefaultValue = true)]
        public decimal ProjectId { get; set; }

        /// <summary>
        /// セッションID
        /// </summary>
        /// <value>セッションID</value>
        /*
        <example>123</example>
        */
        [DataMember(Name = "sessionId", IsRequired = true, EmitDefaultValue = true)]
        public decimal SessionId { get; set; }

        /// <summary>
        /// トークンの有効期限（ISO 8601形式）
        /// </summary>
        /// <value>トークンの有効期限（ISO 8601形式）</value>
        /*
        <example>2024-01-01T12:00:00.000Z</example>
        */
        [DataMember(Name = "expiresAt", IsRequired = true, EmitDefaultValue = true)]
        public string ExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VerifyEmbedTokenResponseDto {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
