/*
 * Ludiscan API Documentation
 *
 * Ludiscan API for game analytics and session tracking
 *
 * The version of the OpenAPI document: 1.32.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace LudiscanApiClient.Runtime.ApiClient.Dto
{
    /// <summary>
    /// VerifyEmbedTokenRequestDto
    /// </summary>
    [DataContract(Name = "VerifyEmbedTokenRequestDto")]
    public partial class VerifyEmbedTokenRequestDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyEmbedTokenRequestDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VerifyEmbedTokenRequestDto()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyEmbedTokenRequestDto" /> class.
        /// </summary>
        /// <param name="token">検証するembedトークン (required).</param>
        public VerifyEmbedTokenRequestDto(string token = default(string))
        {
            // to ensure "token" is required (not null)
            if (token == null)
            {
                throw new ArgumentNullException("token is a required property for VerifyEmbedTokenRequestDto and cannot be null");
            }
            this.Token = token;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// 検証するembedトークン
        /// </summary>
        /// <value>検証するembedトークン</value>
        /*
        <example>eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...</example>
        */
        [DataMember(Name = "token", IsRequired = true, EmitDefaultValue = true)]
        public string Token { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VerifyEmbedTokenRequestDto {\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
